/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export type DashboardClockResponseAction =
  (typeof DashboardClockResponseAction)[keyof typeof DashboardClockResponseAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardClockResponseAction = {
  in: "in",
  out: "out",
  break_start: "break_start",
  break_end: "break_end",
} as const;
