/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export type DashboardResponseClockStatus =
  (typeof DashboardResponseClockStatus)[keyof typeof DashboardResponseClockStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardResponseClockStatus = {
  out: "out",
  in: "in",
  break: "break",
} as const;
