/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export type DashboardResponseStats = {
  avgHours: number;
  avgHoursDiff: number;
  overtimeDiff: number;
  overtimeHours: number;
  remainingDays: number;
  targetHours: number;
  totalHours: number;
  workDays: number;
};
