/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginRequest {
  /**
   * @minLength 1
   * @maxLength 255
   */
  email: string;
  /**
   * @minLength 8
   * @maxLength 255
   * @pattern ^(?=.*[A-Za-z])(?=.*\d).+$
   */
  password: string;
}
