/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Attendance API
 * 勤怠管理API（JWT認証）
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorResponse } from "@/api/__generated__/model/errorResponse";

/**
 * 認証エラー
 */
export type UnauthorizedResponse = ErrorResponse;
