/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

/**
 * ユーザー設定（任意のキーを許容、存在しない場合は null）
 * @nullable
 */
export type UserResponseUserSettings = { [key: string]: unknown } | null;
