/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type {
  LoginBodyBody,
  LoginResponse,
  LogoutResponse,
  UserResponse,
} from ".././model";
import { customInstance } from "../../lib/http/client";

export const getAuth = () => {
  /**
   * メールアドレスとパスワードで認証し、JWTトークンを返す。
   * @summary ログイン
   */
  const login = (loginBodyBody: LoginBodyBody) => {
    return customInstance<LoginResponse>({
      url: `/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginBodyBody,
    });
  };
  /**
   * 現在のJWTトークンを無効化する。
   * @summary ログアウト
   */
  const logout = () => {
    return customInstance<LogoutResponse>({ url: `/logout`, method: "POST" });
  };
  /**
   * 現在認証中のユーザー情報を返す。
   * @summary ログイン中ユーザー情報取得
   */
  const getMe = () => {
    return customInstance<UserResponse>({ url: `/auth/me`, method: "GET" });
  };
  return { login, logout, getMe };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type LoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["login"]>>
>;
export type LogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["logout"]>>
>;
export type GetMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["getMe"]>>
>;
