/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type {
  LoginRequest,
  LoginResponse,
  LogoutApi200,
  UserResponse,
} from ".././model";
import { customInstance } from "../../lib/http/client";

export const getAuth = () => {
  /**
   * @summary ログイン
   */
  const loginApi = (loginRequest: LoginRequest) => {
    return customInstance<LoginResponse>({
      url: `/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginRequest,
    });
  };
  /**
   * @summary ログアウト
   */
  const logoutApi = () => {
    return customInstance<LogoutApi200>({ url: `/logout`, method: "POST" });
  };
  /**
   * @summary ログイン中ユーザー情報取得
   */
  const authMeApi = () => {
    return customInstance<UserResponse>({ url: `/authme`, method: "GET" });
  };
  return { loginApi, logoutApi, authMeApi };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type LoginApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["loginApi"]>>
>;
export type LogoutApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["logoutApi"]>>
>;
export type AuthMeApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["authMeApi"]>>
>;
