/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理システムの REST API 定義。
従業員の出退勤・休憩管理、有給休暇・残業の申請承認、
ダッシュボード集計、カレンダー、ユーザー設定を提供する。

## 認証
JWT Bearer トークンを `Authorization: Bearer <token>` ヘッダーで送信する。
`/login` のみ認証不要。それ以外は全て認証必須。

## エラーハンドリング
- 401: トークン無効または期限切れ
- 403: 権限不足（承認権限が必要な操作）
- 404: 指定リソースが存在しない
- 409: 状態の競合（二重打刻など）
- 422: バリデーションエラー（フィールド別メッセージ付き）
- 500: 予期しないサーバーエラー

 * OpenAPI spec version: 1.1.0
 */
import type {
  LoginBodyBody,
  LoginResponse,
  LogoutResponse,
  UserResponse,
} from ".././model";
import { customInstance } from "../../lib/http/client";

export const getAuth = () => {
  /**
   * メールアドレスとパスワードで認証し、JWTトークンを返す。
   * @summary ログイン
   */
  const login = (loginBodyBody: LoginBodyBody) => {
    return customInstance<LoginResponse>({
      url: `/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginBodyBody,
    });
  };
  /**
   * 現在のJWTトークンを無効化する。
   * @summary ログアウト
   */
  const logout = () => {
    return customInstance<LogoutResponse>({ url: `/logout`, method: "POST" });
  };
  /**
   * 現在認証中のユーザー情報を返す。
   * @summary ログイン中ユーザー情報取得
   */
  const getMe = () => {
    return customInstance<UserResponse>({ url: `/auth/me`, method: "GET" });
  };
  return { login, logout, getMe };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type LoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["login"]>>
>;
export type LogoutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["logout"]>>
>;
export type GetMeResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["getMe"]>>
>;
