/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { SettingsResponse, UpdateSettingsRequest } from ".././model";
import { customInstance } from "../../client";

export const getSettings = () => {
  /**
   * @summary ユーザー設定取得
   */
  const getSettingsApi = () => {
    return customInstance<SettingsResponse>({
      url: `/settings`,
      method: "GET",
    });
  };
  /**
   * @summary ユーザー設定更新
   */
  const updateSettingsApi = (updateSettingsRequest: UpdateSettingsRequest) => {
    return customInstance<SettingsResponse>({
      url: `/settings`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateSettingsRequest,
    });
  };
  return { getSettingsApi, updateSettingsApi };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetSettingsApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSettings>["getSettingsApi"]>>
>;
export type UpdateSettingsApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSettings>["updateSettingsApi"]>>
>;
