/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ApprovalListResponse,
  CreateOvertimeRequestBodyBody,
  CreatePaidLeaveRequestBodyBody,
  OvertimeRequestResponse,
  PaidLeaveRequestResponse,
} from ".././model";
import { customInstance } from "../../lib/http/client";

export const getApproval = () => {
  /**
   * @summary 申請・承認一覧取得
   */
  const getApprovalListApi = () => {
    return customInstance<ApprovalListResponse>({
      url: `/approval`,
      method: "GET",
    });
  };
  /**
   * @summary 有給休暇申請
   */
  const createPaidLeaveRequestApi = (
    createPaidLeaveRequestBodyBody: CreatePaidLeaveRequestBodyBody,
  ) => {
    return customInstance<PaidLeaveRequestResponse>({
      url: `/approval/paid-leaves`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPaidLeaveRequestBodyBody,
    });
  };
  /**
   * @summary 有給休暇申請承認
   */
  const approvePaidLeaveRequestApi = (paidLeaveRequest: string) => {
    return customInstance<PaidLeaveRequestResponse>({
      url: `/approval/paid-leaves/${paidLeaveRequest}/approve`,
      method: "PATCH",
    });
  };
  /**
   * @summary 有給休暇申請却下
   */
  const rejectPaidLeaveRequestApi = (paidLeaveRequest: string) => {
    return customInstance<PaidLeaveRequestResponse>({
      url: `/approval/paid-leaves/${paidLeaveRequest}/reject`,
      method: "PATCH",
    });
  };
  /**
   * @summary 有給休暇申請キャンセル
   */
  const cancelPaidLeaveRequestApi = (paidLeaveRequest: string) => {
    return customInstance<PaidLeaveRequestResponse>({
      url: `/approval/paid-leaves/${paidLeaveRequest}/cancel`,
      method: "PATCH",
    });
  };
  /**
   * @summary 残業申請
   */
  const createOvertimeRequestApi = (
    createOvertimeRequestBodyBody: CreateOvertimeRequestBodyBody,
  ) => {
    return customInstance<OvertimeRequestResponse>({
      url: `/approval/overtime-requests`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createOvertimeRequestBodyBody,
    });
  };
  /**
   * @summary 残業申請承認
   */
  const approveOvertimeRequestApi = (overtimeRequest: string) => {
    return customInstance<OvertimeRequestResponse>({
      url: `/approval/overtime-requests/${overtimeRequest}/approve`,
      method: "PATCH",
    });
  };
  /**
   * @summary 残業申請差戻し
   */
  const returnOvertimeRequestApi = (overtimeRequest: string) => {
    return customInstance<OvertimeRequestResponse>({
      url: `/approval/overtime-requests/${overtimeRequest}/return`,
      method: "PATCH",
    });
  };
  /**
   * @summary 残業申請キャンセル
   */
  const cancelOvertimeRequestApi = (overtimeRequest: string) => {
    return customInstance<OvertimeRequestResponse>({
      url: `/approval/overtime-requests/${overtimeRequest}/cancel`,
      method: "PATCH",
    });
  };
  return {
    getApprovalListApi,
    createPaidLeaveRequestApi,
    approvePaidLeaveRequestApi,
    rejectPaidLeaveRequestApi,
    cancelPaidLeaveRequestApi,
    createOvertimeRequestApi,
    approveOvertimeRequestApi,
    returnOvertimeRequestApi,
    cancelOvertimeRequestApi,
  };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetApprovalListApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApproval>["getApprovalListApi"]>>
>;
export type CreatePaidLeaveRequestApiResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getApproval>["createPaidLeaveRequestApi"]>
  >
>;
export type ApprovePaidLeaveRequestApiResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getApproval>["approvePaidLeaveRequestApi"]>
  >
>;
export type RejectPaidLeaveRequestApiResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getApproval>["rejectPaidLeaveRequestApi"]>
  >
>;
export type CancelPaidLeaveRequestApiResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getApproval>["cancelPaidLeaveRequestApi"]>
  >
>;
export type CreateOvertimeRequestApiResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getApproval>["createOvertimeRequestApi"]>
  >
>;
export type ApproveOvertimeRequestApiResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getApproval>["approveOvertimeRequestApi"]>
  >
>;
export type ReturnOvertimeRequestApiResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getApproval>["returnOvertimeRequestApi"]>
  >
>;
export type CancelOvertimeRequestApiResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getApproval>["cancelOvertimeRequestApi"]>
  >
>;
