/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ApprovalListResponse,
  CreateOvertimeRequestBodyBody,
  CreatePaidLeaveRequestBodyBody,
  OvertimeRequestResponse,
  PaidLeaveRequestResponse,
} from ".././model";
import { customInstance } from "../../lib/http/client";

export const getApproval = () => {
  /**
   * 自分の申請一覧と、承認権限がある場合は承認待ちの申請一覧を返す。
   * @summary 申請・承認一覧取得
   */
  const listApprovals = () => {
    return customInstance<ApprovalListResponse>({
      url: `/approvals`,
      method: "GET",
    });
  };
  /**
   * 有給休暇の取得を申請する。
   * @summary 有給休暇申請
   */
  const createPaidLeaveRequest = (
    createPaidLeaveRequestBodyBody: CreatePaidLeaveRequestBodyBody,
  ) => {
    return customInstance<PaidLeaveRequestResponse>({
      url: `/approvals/paid-leaves`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPaidLeaveRequestBodyBody,
    });
  };
  /**
   * 指定された有給休暇申請を承認する。承認権限が必要。
   * @summary 有給休暇申請承認
   */
  const approvePaidLeaveRequest = (paidLeaveRequestId: string) => {
    return customInstance<PaidLeaveRequestResponse>({
      url: `/approvals/paid-leaves/${paidLeaveRequestId}/approve`,
      method: "PATCH",
    });
  };
  /**
   * 指定された有給休暇申請を却下する。承認権限が必要。
   * @summary 有給休暇申請却下
   */
  const rejectPaidLeaveRequest = (paidLeaveRequestId: string) => {
    return customInstance<PaidLeaveRequestResponse>({
      url: `/approvals/paid-leaves/${paidLeaveRequestId}/reject`,
      method: "PATCH",
    });
  };
  /**
   * 自分の有給休暇申請をキャンセルする。
   * @summary 有給休暇申請キャンセル
   */
  const cancelPaidLeaveRequest = (paidLeaveRequestId: string) => {
    return customInstance<PaidLeaveRequestResponse>({
      url: `/approvals/paid-leaves/${paidLeaveRequestId}/cancel`,
      method: "PATCH",
    });
  };
  /**
   * 残業の事前申請を行う。
   * @summary 残業申請
   */
  const createOvertimeRequest = (
    createOvertimeRequestBodyBody: CreateOvertimeRequestBodyBody,
  ) => {
    return customInstance<OvertimeRequestResponse>({
      url: `/approvals/overtime-requests`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createOvertimeRequestBodyBody,
    });
  };
  /**
   * 指定された残業申請を承認する。承認権限が必要。
   * @summary 残業申請承認
   */
  const approveOvertimeRequest = (overtimeRequestId: string) => {
    return customInstance<OvertimeRequestResponse>({
      url: `/approvals/overtime-requests/${overtimeRequestId}/approve`,
      method: "PATCH",
    });
  };
  /**
   * 指定された残業申請を差し戻す。承認権限が必要。
   * @summary 残業申請差戻し
   */
  const returnOvertimeRequest = (overtimeRequestId: string) => {
    return customInstance<OvertimeRequestResponse>({
      url: `/approvals/overtime-requests/${overtimeRequestId}/return`,
      method: "PATCH",
    });
  };
  /**
   * 自分の残業申請をキャンセルする。
   * @summary 残業申請キャンセル
   */
  const cancelOvertimeRequest = (overtimeRequestId: string) => {
    return customInstance<OvertimeRequestResponse>({
      url: `/approvals/overtime-requests/${overtimeRequestId}/cancel`,
      method: "PATCH",
    });
  };
  return {
    listApprovals,
    createPaidLeaveRequest,
    approvePaidLeaveRequest,
    rejectPaidLeaveRequest,
    cancelPaidLeaveRequest,
    createOvertimeRequest,
    approveOvertimeRequest,
    returnOvertimeRequest,
    cancelOvertimeRequest,
  };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type ListApprovalsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApproval>["listApprovals"]>>
>;
export type CreatePaidLeaveRequestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApproval>["createPaidLeaveRequest"]>>
>;
export type ApprovePaidLeaveRequestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApproval>["approvePaidLeaveRequest"]>>
>;
export type RejectPaidLeaveRequestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApproval>["rejectPaidLeaveRequest"]>>
>;
export type CancelPaidLeaveRequestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApproval>["cancelPaidLeaveRequest"]>>
>;
export type CreateOvertimeRequestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApproval>["createOvertimeRequest"]>>
>;
export type ApproveOvertimeRequestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApproval>["approveOvertimeRequest"]>>
>;
export type ReturnOvertimeRequestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApproval>["returnOvertimeRequest"]>>
>;
export type CancelOvertimeRequestResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getApproval>["cancelOvertimeRequest"]>>
>;
