openapi: 3.0.3

info:
  title: TimeAttendance API
  version: 1.0.0
  description: 勤怠管理API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: "{scheme}://{host}/api"
    description: API Server
    variables:
      scheme:
        default: http
        enum: [http, https]
      host:
        default: localhost:8000
        enum:
          - localhost:8000
          - api.example.com

tags:
  - name: Attendance
    description: 勤怠に関するAPI
  - name: Auth
    description: 認証管理API
  - name: Dashboard
    description: ダッシュボードAPI
  - name: Schedule
    description: スケジュールAPI
  - name: Team
    description: チームAPI
  - name: Settings
    description: 設定API

paths:
  /login:
    $ref: './paths/auth.yaml#/login'
  /logout:
    $ref: './paths/auth.yaml#/logout'
  /authme:
    $ref: './paths/auth.yaml#/authMe'
  /attendances/attendance:
    $ref: './paths/attendance.yaml#/attendance'
  /attendances/clock-in:
    $ref: './paths/attendance.yaml#/clockIn'
  /attendances/clock-out:
    $ref: './paths/attendance.yaml#/clockOut'
  /dashboard:
    $ref: './paths/dashboard.yaml#/dashboard'
  /auth/calendar:
    $ref: './paths/schedule.yaml#/calendar'
  /team/members:
    $ref: './paths/team.yaml#/teamMembers'
  /settings:
    $ref: './paths/settings.yaml#/settings'

components:
  responses:
    $ref: './components/responses.yaml'
  securitySchemes:
    $ref: './components/securitySchemes.yaml'

security:
  - BearerAuth: []