/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardClockBodyBody, DashboardResponse } from ".././model";
import { customInstance } from "../../lib/http/client";

export const getDashboard = () => {
  /**
   * 当月の勤怠統計・今日の勤怠・直近の勤怠記録をまとめて返す。
   * @summary ダッシュボード集計取得
   */
  const getDashboard = () => {
    return customInstance<DashboardResponse>({
      url: `/dashboard`,
      method: "GET",
    });
  };
  /**
   * ダッシュボードからの打刻操作を実行し、更新後のダッシュボード情報を返す。
   * @summary 打刻アクション（出勤・退勤・休憩開始・休憩終了）
   */
  const createDashboardClock = (
    dashboardClockBodyBody: DashboardClockBodyBody,
  ) => {
    return customInstance<DashboardResponse>({
      url: `/dashboard/clock`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: dashboardClockBodyBody,
    });
  };
  return { getDashboard, createDashboardClock };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetDashboardResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDashboard>["getDashboard"]>>
>;
export type CreateDashboardClockResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDashboard>["createDashboardClock"]>>
>;
