/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardClockBodyBody, DashboardResponse } from ".././model";
import { customInstance } from "../../lib/http/client";

export const getDashboard = () => {
  /**
   * @summary ダッシュボード集計取得
   */
  const getDashboardApi = () => {
    return customInstance<DashboardResponse>({
      url: `/dashboard`,
      method: "GET",
    });
  };
  /**
   * @summary 打刻アクション（出勤・退勤・休憩開始・休憩終了）
   */
  const dashboardClockApi = (
    dashboardClockBodyBody: DashboardClockBodyBody,
  ) => {
    return customInstance<DashboardResponse>({
      url: `/dashboard/clock`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: dashboardClockBodyBody,
    });
  };
  return { getDashboardApi, dashboardClockApi };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetDashboardApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDashboard>["getDashboardApi"]>>
>;
export type DashboardClockApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDashboard>["dashboardClockApi"]>>
>;
