/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理システムの REST API 定義。
従業員の出退勤・休憩管理、
ダッシュボード集計、カレンダー、ユーザー設定を提供する。

## 認証
JWT Bearer トークンを `Authorization: Bearer <token>` ヘッダーで送信する。
`/login` のみ認証不要。それ以外は全て認証必須。

## エラーハンドリング
- 401: トークン無効または期限切れ
- 403: 権限不足
- 404: 指定リソースが存在しない
- 409: 状態の競合（二重打刻など）
- 422: バリデーションエラー（フィールド別メッセージ付き）
- 500: 予期しないサーバーエラー

 * OpenAPI spec version: 1.1.0
 */
import type { DashboardResponse } from ".././model";
import { customInstance } from "../../lib/http/client";

export const getDashboard = () => {
  /**
   * 当月の勤怠統計・今日の勤怠・直近の勤怠記録をまとめて返す。
   * @summary ダッシュボード集計取得
   */
  const getDashboard = () => {
    return customInstance<DashboardResponse>({
      url: `/dashboard`,
      method: "GET",
    });
  };
  return { getDashboard };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetDashboardResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDashboard>["getDashboard"]>>
>;
