/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { TeamMembersResponse } from ".././model";
import { customInstance } from "../../lib/http/client";

export const getTeam = () => {
  /**
   * @summary チームメンバー一覧取得
   */
  const getTeamMembersApi = () => {
    return customInstance<TeamMembersResponse>({
      url: `/team/members`,
      method: "GET",
    });
  };
  return { getTeamMembersApi };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetTeamMembersApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTeam>["getTeamMembersApi"]>>
>;
