/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ChangePasswordBodyBody,
  ListLoginHistories200,
  ListLoginHistoriesParams,
  SettingsResponse,
  UpdateSettingsBodyBody,
} from ".././model";
import { customInstance } from "../../lib/http/client";

export const getSettings = () => {
  /**
   * ログインユーザーのプロフィール・通知・セキュリティ設定を返す。
   * @summary ユーザー設定取得
   */
  const getSettings = () => {
    return customInstance<SettingsResponse>({
      url: `/settings`,
      method: "GET",
    });
  };
  /**
   * プロフィール・通知・テーマ・言語設定を更新する。
   * @summary ユーザー設定更新
   */
  const updateSettings = (updateSettingsBodyBody: UpdateSettingsBodyBody) => {
    return customInstance<SettingsResponse>({
      url: `/settings`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateSettingsBodyBody,
    });
  };
  /**
   * 現在のパスワードを検証し、新しいパスワードに変更する。
   * @summary パスワード変更
   */
  const updatePassword = (changePasswordBodyBody: ChangePasswordBodyBody) => {
    return customInstance<SettingsResponse>({
      url: `/settings/password`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: changePasswordBodyBody,
    });
  };
  /**
   * ログインユーザーのログイン履歴を新しい順に返す。
   * @summary ログイン履歴一覧取得
   */
  const listLoginHistories = (params?: ListLoginHistoriesParams) => {
    return customInstance<ListLoginHistories200>({
      url: `/settings/login-histories`,
      method: "GET",
      params,
    });
  };
  return { getSettings, updateSettings, updatePassword, listLoginHistories };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetSettingsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSettings>["getSettings"]>>
>;
export type UpdateSettingsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSettings>["updateSettings"]>>
>;
export type UpdatePasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSettings>["updatePassword"]>>
>;
export type ListLoginHistoriesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSettings>["listLoginHistories"]>>
>;
