/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type {
  ChangePasswordBodyBody,
  LoginHistoryResponse,
  SettingsResponse,
  UpdateSettingsBodyBody,
} from ".././model";
import { customInstance } from "../../lib/http/client";

export const getSettings = () => {
  /**
   * @summary ユーザー設定取得
   */
  const getSettingsApi = () => {
    return customInstance<SettingsResponse>({
      url: `/settings`,
      method: "GET",
    });
  };
  /**
   * @summary ユーザー設定更新
   */
  const updateSettingsApi = (
    updateSettingsBodyBody: UpdateSettingsBodyBody,
  ) => {
    return customInstance<SettingsResponse>({
      url: `/settings`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: updateSettingsBodyBody,
    });
  };
  /**
   * @summary パスワード変更
   */
  const changePasswordApi = (
    changePasswordBodyBody: ChangePasswordBodyBody,
  ) => {
    return customInstance<SettingsResponse>({
      url: `/settings/password`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: changePasswordBodyBody,
    });
  };
  /**
   * @summary ログイン履歴一覧取得
   */
  const getLoginHistoriesApi = () => {
    return customInstance<LoginHistoryResponse[]>({
      url: `/settings/login-histories`,
      method: "GET",
    });
  };
  return {
    getSettingsApi,
    updateSettingsApi,
    changePasswordApi,
    getLoginHistoriesApi,
  };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetSettingsApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSettings>["getSettingsApi"]>>
>;
export type UpdateSettingsApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSettings>["updateSettingsApi"]>>
>;
export type ChangePasswordApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSettings>["changePasswordApi"]>>
>;
export type GetLoginHistoriesApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSettings>["getLoginHistoriesApi"]>>
>;
