/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Attendance API
 * 勤怠管理API（JWT認証）
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  Attendance,
  ConflictResponse,
  ServerErrorResponse,
  UnauthorizedResponse,
  ValidationErrorResponse,
} from "@/api/__generated__/model";
import { customInstance } from "@/api/client";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary 今日の勤怠取得
 */
export const todayApi = (signal?: AbortSignal) => {
  return customInstance<Attendance>({
    url: `/attendances/today`,
    method: "GET",
    signal,
  });
};

export const getTodayApiQueryKey = () => {
  return [`/attendances/today`] as const;
};

export const getTodayApiQueryOptions = <
  TData = Awaited<ReturnType<typeof todayApi>>,
  TError = UnauthorizedResponse | ServerErrorResponse,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof todayApi>>, TError, TData>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTodayApiQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof todayApi>>> = ({
    signal,
  }) => todayApi(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof todayApi>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type TodayApiQueryResult = NonNullable<
  Awaited<ReturnType<typeof todayApi>>
>;
export type TodayApiQueryError = UnauthorizedResponse | ServerErrorResponse;

/**
 * @summary 今日の勤怠取得
 */
export const useTodayApi = <
  TData = Awaited<ReturnType<typeof todayApi>>,
  TError = UnauthorizedResponse | ServerErrorResponse,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof todayApi>>, TError, TData>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getTodayApiQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary 出勤打刻
 */
export const clockInApi = () => {
  return customInstance<Attendance>({
    url: `/attendances/clock-in`,
    method: "POST",
  });
};

export const getClockInApiMutationOptions = <
  TError =
    | UnauthorizedResponse
    | ConflictResponse
    | ValidationErrorResponse
    | ServerErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clockInApi>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clockInApi>>,
  TError,
  void,
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clockInApi>>,
    void
  > = () => {
    return clockInApi();
  };

  return { mutationFn, ...mutationOptions };
};

export type ClockInApiMutationResult = NonNullable<
  Awaited<ReturnType<typeof clockInApi>>
>;

export type ClockInApiMutationError =
  | UnauthorizedResponse
  | ConflictResponse
  | ValidationErrorResponse
  | ServerErrorResponse;

/**
 * @summary 出勤打刻
 */
export const useClockInApi = <
  TError =
    | UnauthorizedResponse
    | ConflictResponse
    | ValidationErrorResponse
    | ServerErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clockInApi>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof clockInApi>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getClockInApiMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * @summary 退勤打刻
 */
export const clockOutApi = () => {
  return customInstance<Attendance>({
    url: `/attendances/clock-out`,
    method: "POST",
  });
};

export const getClockOutApiMutationOptions = <
  TError =
    | UnauthorizedResponse
    | ConflictResponse
    | ValidationErrorResponse
    | ServerErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clockOutApi>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof clockOutApi>>,
  TError,
  void,
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof clockOutApi>>,
    void
  > = () => {
    return clockOutApi();
  };

  return { mutationFn, ...mutationOptions };
};

export type ClockOutApiMutationResult = NonNullable<
  Awaited<ReturnType<typeof clockOutApi>>
>;

export type ClockOutApiMutationError =
  | UnauthorizedResponse
  | ConflictResponse
  | ValidationErrorResponse
  | ServerErrorResponse;

/**
 * @summary 退勤打刻
 */
export const useClockOutApi = <
  TError =
    | UnauthorizedResponse
    | ConflictResponse
    | ValidationErrorResponse
    | ServerErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof clockOutApi>>,
    TError,
    void,
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof clockOutApi>>,
  TError,
  void,
  TContext
> => {
  const mutationOptions = getClockOutApiMutationOptions(options);

  return useMutation(mutationOptions);
};
