/**
 * This file was auto-generated by openapi-zod.
 * Do not make direct changes to the file.
 */


import { z } from 'zod';

export namespace components.schemas {
  /**
   * @description 打刻アクション種別 
   * @enum {string}
   */
  export const ClockAction = z.enum(["in", "out", "break_start", "break_end"]);
  /**
   * @description 現在の打刻状態 
   * @enum {string}
   */
  export const ClockStatus = z.enum(["out", "in", "break"]);
  /**
   * @description UIテーマ設定 
   * @enum {string}
   */
  export const ThemeType = z.enum(["light", "dark"]);
  /**
   * @description 表示言語コード 
   * @enum {string}
   */
  export const LanguageCode = z.enum(["ja", "en"]);
  /**
   * @description カレンダー日付の勤務状態 
   * @enum {string}
   */
  export const CalendarDayStatus = z.enum(["working", "off", "holiday", "pending"]);
  /**
   * @description チームメンバーの勤務状態 
   * @enum {string}
   */
  export const TeamMemberStatus = z.enum(["working", "break", "off", "leave"]);
  /**
   * @description 勤怠レコードの勤務区分 
   * @enum {string}
   */
  export const AttendanceStatus = z.enum(["working", "out", "break"]);
  /**
   * @description ユーザーアカウントの状態 
   * @enum {string}
   */
  export const UserStatus = z.enum(["active", "inactive"]);
  /**
   * @description 申請のステータス 
   * @enum {string}
   */
  export const ApprovalStatus = z.enum(["pending", "approved", "rejected", "canceled"]);
  /**
   * @description 残業申請のステータス 
   * @enum {string}
   */
  export const OvertimeRequestStatus = z.enum(["pending", "approved", "returned", "canceled"]);
  export const LoginRequest = z.object({
    email: z.string(),
    password: z.string(),
  });
  export const LoginResponse = z.object({
    token: z.string().optional(),
  });
  /** @description ログアウト成功レスポンス */
  export const LogoutResponse = z.object({
    message: z.string().optional(),
  });
  /** @description ユーザー情報 */
  export const UserResponse = z.object({
    user: z.object({
      id: z.string(),
      name: z.string(),
      email: z.string(),
      roles: z.array(z.string()),
      settings: z.object({
        theme: components["schemas"]["ThemeType"].optional(),
        language: components["schemas"]["LanguageCode"].optional(),
      }).nullable().optional(),
    }),
  });
  export const AttendanceClockInRequest = z.object({
    work_date: z.string(),
    start_time: z.string(),
  });
  export const AttendanceClockOutRequest = z.object({
    work_date: z.string(),
    end_time: z.string(),
  });
  export const AttendanceStoreRequest = z.object({
    work_date: z.string(),
    start_time: z.string(),
    end_time: z.string().nullable().optional(),
    note: z.string().nullable().optional(),
  });
  export const AttendanceUpdateRequest = z.object({
    start_time: z.string().nullable().optional(),
    end_time: z.string().nullable().optional(),
    note: z.string().nullable().optional(),
  });
  export const AttendanceResponse = z.object({
    user_id: z.string(),
    work_date: z.string(),
    start_time: z.string().nullable(),
    end_time: z.string().nullable().optional(),
    break_minutes: z.number().int().nullable().optional(),
    worked_minutes: z.number().int().nullable().optional(),
  });
  export const AttendanceIndexRequest = z.object({
    from: z.string(),
    to: z.string(),
  });
  export const DashboardClockRequest = z.object({
    action: components["schemas"]["ClockAction"],
  });
  export const DashboardResponse = z.object({
    user: components["schemas"]["DashboardUser"],
    clockStatus: components["schemas"]["ClockStatus"],
    todayRecord: components["schemas"]["DashboardTodayRecord"],
    stats: components["schemas"]["DashboardStats"],
    recentRecords: z.array(components["schemas"]["DashboardRecentRecord"]),
    pendingOvertimeRequests: z.number().int(),
  });
  /** @description ダッシュボード用ユーザー情報 */
  export const DashboardUser = z.object({
    id: z.string(),
    name: z.string(),
  });
  /** @description 今日の勤怠レコード */
  export const DashboardTodayRecord = z.object({
    clockInTime: z.string().nullable(),
    totalWorkedHours: z.number().nullable(),
  });
  /** @description ダッシュボード月次統計 */
  export const DashboardStats = z.object({
    totalHours: z.number(),
    targetHours: z.number(),
    workDays: z.number().int(),
    remainingDays: z.number().int(),
    avgHours: z.number(),
    avgHoursDiff: z.number(),
    overtimeHours: z.number(),
    overtimeDiff: z.number(),
  });
  /** @description 直近の勤怠レコード */
  export const DashboardRecentRecord = z.object({
    date: z.string(),
    day: z.string(),
    clockIn: z.string().nullable(),
    clockOut: z.string().nullable(),
    workHours: z.number().nullable(),
    status: components["schemas"]["AttendanceStatus"],
  });
  export const CalendarIndexRequest = z.object({
    year: z.number().int(),
    month: z.number().int(),
  });
  export const CalendarResponse = z.object({
    year: z.number().int(),
    month: z.number().int(),
    summary: components["schemas"]["CalendarSummary"],
    days: z.array(components["schemas"]["CalendarDay"]),
  });
  /** @description カレンダー月次サマリー */
  export const CalendarSummary = z.object({
    totalWorkHours: z.number(),
    targetHours: z.number(),
    scheduledWorkDays: z.number().int(),
    overtimeHours: z.number(),
    paidLeaveDays: z.number(),
    remainingPaidLeaveDays: z.number(),
  });
  /** @description カレンダー1日分の情報 */
  export const CalendarDay = z.object({
    date: z.string(),
    label: z.string(),
    dayOfWeek: z.string(),
    status: components["schemas"]["CalendarDayStatus"],
    shift: z.string().nullable().optional(),
    timeRange: z.string().nullable().optional(),
    location: z.string().nullable().optional(),
    note: z.string().nullable().optional(),
    isToday: z.boolean(),
    isHoliday: z.boolean(),
  });
  export const SettingsResponse = z.object({
    profile: components["schemas"]["SettingsProfile"],
    notifications: components["schemas"]["SettingsNotifications"],
    security: components["schemas"]["SettingsSecurity"],
    theme: components["schemas"]["ThemeType"],
    language: components["schemas"]["LanguageCode"],
  });
  export const UpdateSettingsRequest = z.object({
    profile: components["schemas"]["UpdateSettingsProfile"],
    notifications: components["schemas"]["SettingsNotifications"],
    theme: components["schemas"]["ThemeType"],
    language: components["schemas"]["LanguageCode"],
  });
  /** @description ユーザープロフィール情報（レスポンス用） */
  export const SettingsProfile = z.object({
    name: z.string(),
    email: z.string(),
    department: z.string(),
    role: z.string(),
    employeeCode: z.string(),
  });
  /** @description ユーザープロフィール更新（リクエスト用） */
  export const UpdateSettingsProfile = z.object({
    name: z.string(),
    email: z.string(),
  });
  export const ChangePasswordRequest = z.object({
    current_password: z.string(),
    new_password: z.string(),
    new_password_confirmation: z.string(),
  });
  export const LoginHistoryResponse = z.object({
    id: z.string(),
    ipAddress: z.string().nullable(),
    userAgent: z.string().nullable(),
    loggedInAt: z.string(),
    loggedOutAt: z.string().nullable().optional(),
  });
  /** @description 通知設定 */
  export const SettingsNotifications = z.object({
    clockInReminder: z.boolean(),
    approvalNotification: z.boolean(),
    leaveReminder: z.boolean(),
  });
  /** @description セキュリティ設定 */
  export const SettingsSecurity = z.object({
    twoFactorEnabled: z.boolean(),
    emailVerified: z.boolean(),
    lastLoginAt: z.string().nullable().optional(),
    passwordLastChangedAt: z.string().nullable().optional(),
  });
  export const TeamMembersResponse = z.object({
    members: z.array(components["schemas"]["TeamMember"]),
  });
  /** @description チームメンバー情報 */
  export const TeamMember = z.object({
    id: z.string(),
    name: z.string(),
    role: z.string(),
    department: z.string(),
    status: components["schemas"]["TeamMemberStatus"],
    clockInTime: z.string().nullable().optional(),
    email: z.string(),
  });
  export const ApprovalListResponse = z.object({
    paidLeaveRequests: z.array(components["schemas"]["PaidLeaveRequestResponse"]),
    overtimeRequests: z.array(components["schemas"]["OvertimeRequestResponse"]),
    pendingPaidLeaveRequests: z.array(components["schemas"]["PaidLeaveRequestResponse"]),
    pendingOvertimeRequests: z.array(components["schemas"]["OvertimeRequestResponse"]),
    paidLeaveSummary: components["schemas"]["PaidLeaveSummary"],
    isApprover: z.boolean(),
  });
  export const PaidLeaveRequestResponse = z.object({
    id: z.string(),
    userId: z.string(),
    leaveDate: z.string(),
    days: z.number(),
    status: components["schemas"]["ApprovalStatus"],
    reason: z.string().nullable(),
    approvedBy: z.string().nullable(),
    approvedAt: z.string().nullable(),
    createdAt: z.string(),
  });
  export const CreatePaidLeaveRequest = z.object({
    leave_date: z.string(),
    days: z.number(),
    reason: z.string().nullable().optional(),
  });
  export const OvertimeRequestResponse = z.object({
    id: z.string(),
    userId: z.string(),
    workDate: z.string(),
    startTime: z.string(),
    endTime: z.string(),
    status: components["schemas"]["OvertimeRequestStatus"],
    reason: z.string().nullable(),
    durationHours: z.number(),
    approvedBy: z.string().nullable(),
    approvedAt: z.string().nullable(),
    createdAt: z.string(),
  });
  export const CreateOvertimeRequest = z.object({
    work_date: z.string(),
    start_time: z.string(),
    end_time: z.string(),
    reason: z.string().nullable().optional(),
  });
  export const PaidLeaveSummary = z.object({
    totalDays: z.number(),
    usedDays: z.number(),
    remainingDays: z.number(),
  });
  export const ErrorResponse = z.object({
    message: z.string().optional(),
  });
  export const ValidationErrorResponse = z.object({
    message: z.string().optional(),
    errors: z.record(z.string(), z.array(z.string())).optional(),
  });
}
export namespace components.responses {
  /** @description 認証エラー */
  export const Unauthorized = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description バリデーションエラー */
  export const ValidationError = {
    content: {
      "application/json": components["schemas"]["ValidationErrorResponse"],
    },
  };
  /** @description サーバーエラー */
  export const InternalServerError = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description 排他エラー */
  export const Conflict = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description リソース未存在エラー */
  export const NotFound = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description 認可エラー */
  export const Forbidden = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
}
export namespace components.parameters {
  /** @description 検索期間の開始日 */
  export const QueryDateFrom = z.string();
  /** @description 検索期間の終了日 */
  export const QueryDateTo = z.string();
  /** @description 勤怠レコードID */
  export const PathAttendanceId = z.string();
  /** @description 対象年 */
  export const QueryYear = z.number().int();
  /** @description 対象月 */
  export const QueryMonth = z.number().int();
  /** @description 有給休暇申請ID */
  export const PathPaidLeaveRequestId = z.string();
  /** @description 残業申請ID */
  export const PathOvertimeRequestId = z.string();
}
export namespace components.requestBodies {
  export const LoginBody = {
    content: {
      "application/json": components["schemas"]["LoginRequest"],
    },
  };
  export const AttendanceClockInBody = {
    content: {
      "application/json": components["schemas"]["AttendanceClockInRequest"],
    },
  };
  export const AttendanceClockOutBody = {
    content: {
      "application/json": components["schemas"]["AttendanceClockOutRequest"],
    },
  };
  export const AttendanceStoreBody = {
    content: {
      "application/json": components["schemas"]["AttendanceStoreRequest"],
    },
  };
  export const AttendanceUpdateBody = {
    content: {
      "application/json": components["schemas"]["AttendanceUpdateRequest"],
    },
  };
  export const DashboardClockBody = {
    content: {
      "application/json": components["schemas"]["DashboardClockRequest"],
    },
  };
  export const UpdateSettingsBody = {
    content: {
      "application/json": components["schemas"]["UpdateSettingsRequest"],
    },
  };
  export const ChangePasswordBody = {
    content: {
      "application/json": components["schemas"]["ChangePasswordRequest"],
    },
  };
  export const CreatePaidLeaveRequestBody = {
    content: {
      "application/json": components["schemas"]["CreatePaidLeaveRequest"],
    },
  };
  export const CreateOvertimeRequestBody = {
    content: {
      "application/json": components["schemas"]["CreateOvertimeRequest"],
    },
  };
}

export const operations = {

  loginApi: {
    /** ログイン */
    requestBody: components["requestBodies"]["LoginBody"],
    responses: {
      /** @description ログイン成功 */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  logoutApi: {
    /** ログアウト */
    responses: {
      /** @description ログアウト成功 */
      200: {
        content: {
          "application/json": components["schemas"]["LogoutResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  authMeApi: {
    /** ログイン中ユーザー情報取得 */
    responses: {
      /** @description 認証済みユーザー情報 */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  todayAttendanceApi: {
    /** 今日の勤怠取得 */
    responses: {
      /** @description 今日の勤怠情報 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  clockInApi: {
    /** 出勤打刻 */
    requestBody: components["requestBodies"]["AttendanceClockInBody"],
    responses: {
      /** @description 出勤成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  clockOutApi: {
    /** 退勤打刻 */
    requestBody: components["requestBodies"]["AttendanceClockOutBody"],
    responses: {
      /** @description 退勤成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  listAttendancesApi: {
    /** 勤怠一覧取得 */
    responses: {
      /** @description 勤怠一覧 */
      200: {
        content: {
          "application/json": z.array(components["schemas"]["AttendanceResponse"]),
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  storeAttendanceApi: {
    /** 勤怠の新規登録 */
    requestBody: components["requestBodies"]["AttendanceStoreBody"],
    responses: {
      /** @description 登録成功 */
      201: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  updateAttendanceApi: {
    /** 勤怠の更新 */
    requestBody: components["requestBodies"]["AttendanceUpdateBody"],
    responses: {
      /** @description 更新成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      404: components["responses"]["NotFound"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getDashboardApi: {
    /** ダッシュボード集計取得 */
    responses: {
      /** @description ダッシュボード情報 */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  dashboardClockApi: {
    /** 打刻アクション（出勤・退勤・休憩開始・休憩終了） */
    requestBody: components["requestBodies"]["DashboardClockBody"],
    responses: {
      /** @description 打刻成功 */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getCalendarApi: {
    /** 月次カレンダー取得 */
    responses: {
      /** @description 対象月の日付一覧 */
      200: {
        content: {
          "application/json": components["schemas"]["CalendarResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getTeamMembersApi: {
    /** チームメンバー一覧取得 */
    responses: {
      /** @description チームメンバー一覧 */
      200: {
        content: {
          "application/json": components["schemas"]["TeamMembersResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getSettingsApi: {
    /** ユーザー設定取得 */
    responses: {
      /** @description ユーザー設定 */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  updateSettingsApi: {
    /** ユーザー設定更新 */
    requestBody: components["requestBodies"]["UpdateSettingsBody"],
    responses: {
      /** @description 更新後ユーザー設定 */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  changePasswordApi: {
    /** パスワード変更 */
    requestBody: components["requestBodies"]["ChangePasswordBody"],
    responses: {
      /** @description パスワード変更成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getLoginHistoriesApi: {
    /** ログイン履歴一覧取得 */
    responses: {
      /** @description ログイン履歴一覧 */
      200: {
        content: {
          "application/json": z.array(components["schemas"]["LoginHistoryResponse"]),
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getApprovalListApi: {
    /** 申請・承認一覧取得 */
    responses: {
      /** @description 申請一覧 */
      200: {
        content: {
          "application/json": components["schemas"]["ApprovalListResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  createPaidLeaveRequestApi: {
    /** 有給休暇申請 */
    requestBody: components["requestBodies"]["CreatePaidLeaveRequestBody"],
    responses: {
      /** @description 申請成功 */
      201: {
        content: {
          "application/json": components["schemas"]["PaidLeaveRequestResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  approvePaidLeaveRequestApi: {
    /** 有給休暇申請承認 */
    responses: {
      /** @description 承認成功 */
      200: {
        content: {
          "application/json": components["schemas"]["PaidLeaveRequestResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      403: components["responses"]["Forbidden"],
      404: components["responses"]["NotFound"],
      500: components["responses"]["InternalServerError"],
    },
  },
  rejectPaidLeaveRequestApi: {
    /** 有給休暇申請却下 */
    responses: {
      /** @description 却下成功 */
      200: {
        content: {
          "application/json": components["schemas"]["PaidLeaveRequestResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      403: components["responses"]["Forbidden"],
      404: components["responses"]["NotFound"],
      500: components["responses"]["InternalServerError"],
    },
  },
  cancelPaidLeaveRequestApi: {
    /** 有給休暇申請キャンセル */
    responses: {
      /** @description キャンセル成功 */
      200: {
        content: {
          "application/json": components["schemas"]["PaidLeaveRequestResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      403: components["responses"]["Forbidden"],
      404: components["responses"]["NotFound"],
      500: components["responses"]["InternalServerError"],
    },
  },
  createOvertimeRequestApi: {
    /** 残業申請 */
    requestBody: components["requestBodies"]["CreateOvertimeRequestBody"],
    responses: {
      /** @description 申請成功 */
      201: {
        content: {
          "application/json": components["schemas"]["OvertimeRequestResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  approveOvertimeRequestApi: {
    /** 残業申請承認 */
    responses: {
      /** @description 承認成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OvertimeRequestResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      403: components["responses"]["Forbidden"],
      404: components["responses"]["NotFound"],
      500: components["responses"]["InternalServerError"],
    },
  },
  returnOvertimeRequestApi: {
    /** 残業申請差戻し */
    responses: {
      /** @description 差戻し成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OvertimeRequestResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      403: components["responses"]["Forbidden"],
      404: components["responses"]["NotFound"],
      500: components["responses"]["InternalServerError"],
    },
  },
  cancelOvertimeRequestApi: {
    /** 残業申請キャンセル */
    responses: {
      /** @description キャンセル成功 */
      200: {
        content: {
          "application/json": components["schemas"]["OvertimeRequestResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      403: components["responses"]["Forbidden"],
      404: components["responses"]["NotFound"],
      500: components["responses"]["InternalServerError"],
    },
  },
}

export const paths = {
  "/login": {
    /** ログイン */
    post: operations["loginApi"],
  },
  "/logout": {
    /** ログアウト */
    post: operations["logoutApi"],
  },
  "/authme": {
    /** ログイン中ユーザー情報取得 */
    get: operations["authMeApi"],
  },
  "/attendances/attendance": {
    /** 今日の勤怠取得 */
    get: operations["todayAttendanceApi"],
  },
  "/attendances/clock-in": {
    /** 出勤打刻 */
    post: operations["clockInApi"],
  },
  "/attendances/clock-out": {
    /** 退勤打刻 */
    post: operations["clockOutApi"],
  },
  "/attendances": {
    /** 勤怠一覧取得 */
    get: operations["listAttendancesApi"],
    /** 勤怠の新規登録 */
    post: operations["storeAttendanceApi"],
  },
  "/attendances/{attendance}": {
    /** 勤怠の更新 */
    patch: operations["updateAttendanceApi"],
  },
  "/dashboard": {
    /** ダッシュボード集計取得 */
    get: operations["getDashboardApi"],
  },
  "/dashboard/clock": {
    /** 打刻アクション（出勤・退勤・休憩開始・休憩終了） */
    post: operations["dashboardClockApi"],
  },
  "/auth/calendar": {
    /** 月次カレンダー取得 */
    get: operations["getCalendarApi"],
  },
  "/team/members": {
    /** チームメンバー一覧取得 */
    get: operations["getTeamMembersApi"],
  },
  "/settings": {
    /** ユーザー設定取得 */
    get: operations["getSettingsApi"],
    /** ユーザー設定更新 */
    put: operations["updateSettingsApi"],
  },
  "/settings/password": {
    /** パスワード変更 */
    put: operations["changePasswordApi"],
  },
  "/settings/login-histories": {
    /** ログイン履歴一覧取得 */
    get: operations["getLoginHistoriesApi"],
  },
  "/approval": {
    /** 申請・承認一覧取得 */
    get: operations["getApprovalListApi"],
  },
  "/approval/paid-leaves": {
    /** 有給休暇申請 */
    post: operations["createPaidLeaveRequestApi"],
  },
  "/approval/paid-leaves/{paidLeaveRequest}/approve": {
    /** 有給休暇申請承認 */
    patch: operations["approvePaidLeaveRequestApi"],
  },
  "/approval/paid-leaves/{paidLeaveRequest}/reject": {
    /** 有給休暇申請却下 */
    patch: operations["rejectPaidLeaveRequestApi"],
  },
  "/approval/paid-leaves/{paidLeaveRequest}/cancel": {
    /** 有給休暇申請キャンセル */
    patch: operations["cancelPaidLeaveRequestApi"],
  },
  "/approval/overtime-requests": {
    /** 残業申請 */
    post: operations["createOvertimeRequestApi"],
  },
  "/approval/overtime-requests/{overtimeRequest}/approve": {
    /** 残業申請承認 */
    patch: operations["approveOvertimeRequestApi"],
  },
  "/approval/overtime-requests/{overtimeRequest}/return": {
    /** 残業申請差戻し */
    patch: operations["returnOvertimeRequestApi"],
  },
  "/approval/overtime-requests/{overtimeRequest}/cancel": {
    /** 残業申請キャンセル */
    patch: operations["cancelOvertimeRequestApi"],
  },
}
