/**
 * This file was auto-generated by openapi-zod.
 * Do not make direct changes to the file.
 */


import { z } from 'zod';

export namespace components.schemas {
  /**
   * @description 打刻アクション種別 
   * @enum {string}
   */
  export const ClockAction = z.enum(["in", "out", "breakStart", "breakEnd"]);
  /**
   * @description 現在の打刻状態 
   * @enum {string}
   */
  export const ClockStatus = z.enum(["out", "in", "break"]);
  /**
   * @description UIテーマ設定 
   * @enum {string}
   */
  export const ThemeType = z.enum(["light", "dark"]);
  /**
   * @description 表示言語コード 
   * @enum {string}
   */
  export const LanguageCode = z.enum(["ja", "en"]);
  /**
   * @description カレンダー日付の勤務状態 
   * @enum {string}
   */
  export const CalendarDayStatus = z.enum(["working", "off", "holiday", "pending"]);
  /**
   * @description チームメンバーの勤務状態 
   * @enum {string}
   */
  export const TeamMemberStatus = z.enum(["working", "break", "off", "leave"]);
  /**
   * @description 勤怠レコードの勤務区分 
   * @enum {string}
   */
  export const AttendanceStatus = z.enum(["working", "out", "break"]);
  /**
   * @description ユーザーアカウントの状態 
   * @enum {string}
   */
  export const UserStatus = z.enum(["active", "inactive"]);
  /** @description ログインのHTTPリクエスト */
  export const LoginRequest = z.object({
    email: z.string(),
    password: z.string(),
  });
  /** @description ログイン成功のHTTPレスポンス */
  export const LoginResponse = z.object({
    token: z.string(),
  });
  /** @description ログアウト成功HTTPレスポンス */
  export const LogoutResponse = z.object({
    message: z.string().optional(),
  });
  /** @description ユーザー情報 */
  export const UserResponse = z.object({
    user: z.object({
      id: z.string(),
      name: z.string(),
      email: z.string(),
      roles: z.array(z.string()),
      settings: z.object({
        theme: components["schemas"]["ThemeType"].optional(),
        language: components["schemas"]["LanguageCode"].optional(),
      }).nullable().optional(),
    }),
  });
  /** @description 出勤打刻のHTTPリクエスト */
  export const AttendanceClockInRequest = z.record(z.string(), z.any());
  /** @description 退勤打刻のHTTPリクエスト */
  export const AttendanceClockOutRequest = z.record(z.string(), z.any());
  /** @description 休憩開始打刻のHTTPリクエスト */
  export const AttendanceBreakStartRequest = z.record(z.string(), z.any());
  /** @description 休憩終了打刻のHTTPリクエスト */
  export const AttendanceBreakEndRequest = z.record(z.string(), z.any());
  /** @description 勤怠の新規作成のHTTPリクエスト */
  export const AttendanceStoreRequest = z.object({
    workDate: z.string(),
    clockInAt: z.string(),
    clockOutAt: z.string().nullable().optional(),
  });
  /** @description 勤怠レコード更新のHTTPリクエスト */
  export const AttendanceUpdateRequest = z.object({
    clockInAt: z.string().nullable().optional(),
    clockOutAt: z.string().nullable().optional(),
    note: z.string().nullable().optional(),
  });
  /** @description 勤怠レコードの表示用のHTTPレスポンス */
  export const AttendanceResponse = z.object({
    id: z.string().optional(),
    userId: z.string(),
    workDate: z.string(),
    clockStatus: components["schemas"]["ClockStatus"],
    clockInAt: z.string().nullable(),
    clockOutAt: z.string().nullable().optional(),
    breakMinutes: z.number().int().nullable().optional(),
    workedMinutes: z.number().int().nullable().optional(),
    overtimeMinutes: z.number().int().nullable().optional(),
  });
  /** @description 勤怠レコード取得のHTTPリクエスト */
  export const AttendanceIndexRequest = z.object({
    from: z.string(),
    to: z.string(),
  });
  export const DashboardResponse = z.object({
    user: components["schemas"]["DashboardUser"],
    clockStatus: components["schemas"]["ClockStatus"],
    todayRecord: components["schemas"]["DashboardTodayRecord"],
    stats: components["schemas"]["DashboardStats"],
    recentRecords: z.array(components["schemas"]["DashboardRecentRecord"]),
  });
  /** @description ダッシュボード用ユーザー情報 */
  export const DashboardUser = z.object({
    id: z.string(),
    name: z.string(),
  });
  /** @description 今日の勤怠レコード */
  export const DashboardTodayRecord = z.object({
    clockInTime: z.string().nullable(),
    totalWorkedHours: z.number().nullable(),
  });
  /** @description ダッシュボード月次統計 */
  export const DashboardStats = z.object({
    totalHours: z.number(),
    targetHours: z.number(),
    workDays: z.number().int(),
    remainingDays: z.number().int(),
    avgHours: z.number(),
    avgHoursDiff: z.number(),
    overtimeHours: z.number(),
    overtimeDiff: z.number(),
  });
  /** @description 直近の勤怠レコード */
  export const DashboardRecentRecord = z.object({
    date: z.string(),
    day: z.string(),
    clockIn: z.string().nullable(),
    clockOut: z.string().nullable(),
    workHours: z.number().nullable(),
    status: components["schemas"]["AttendanceStatus"],
  });
  export const CalendarIndexRequest = z.object({
    year: z.number().int(),
    month: z.number().int(),
  });
  export const CalendarResponse = z.object({
    year: z.number().int(),
    month: z.number().int(),
    summary: components["schemas"]["CalendarSummary"],
    days: z.array(components["schemas"]["CalendarDay"]),
  });
  /** @description カレンダー月次サマリー */
  export const CalendarSummary = z.object({
    totalWorkHours: z.number(),
    targetHours: z.number(),
    scheduledWorkDays: z.number().int(),
    overtimeHours: z.number(),
    paidLeaveDays: z.number(),
    remainingPaidLeaveDays: z.number(),
  });
  /** @description カレンダー1日分の情報 */
  export const CalendarDay = z.object({
    date: z.string(),
    label: z.string(),
    dayOfWeek: z.string(),
    status: components["schemas"]["CalendarDayStatus"],
    shift: z.string().nullable().optional(),
    timeRange: z.string().nullable().optional(),
    location: z.string().nullable().optional(),
    note: z.string().nullable().optional(),
    isToday: z.boolean(),
    isHoliday: z.boolean(),
  });
  export const SettingsResponse = z.object({
    profile: components["schemas"]["SettingsProfile"],
    notifications: components["schemas"]["SettingsNotifications"],
    security: components["schemas"]["SettingsSecurity"],
    theme: components["schemas"]["ThemeType"],
    language: components["schemas"]["LanguageCode"],
  });
  export const UpdateSettingsRequest = z.object({
    profile: components["schemas"]["UpdateSettingsProfile"],
    notifications: components["schemas"]["SettingsNotifications"],
    theme: components["schemas"]["ThemeType"],
    language: components["schemas"]["LanguageCode"],
  });
  /** @description ユーザープロフィール情報（HTTPレスポンス用） */
  export const SettingsProfile = z.object({
    name: z.string(),
    email: z.string(),
    department: z.string(),
    role: z.string(),
    employeeCode: z.string(),
  });
  /** @description ユーザープロフィール更新（HTTPリクエスト用） */
  export const UpdateSettingsProfile = z.object({
    name: z.string(),
    email: z.string(),
  });
  export const ChangePasswordRequest = z.object({
    currentPassword: z.string(),
    newPassword: z.string(),
    newPasswordConfirmation: z.string(),
  });
  export const LoginHistoryResponse = z.object({
    id: z.string(),
    ipAddress: z.string().nullable(),
    userAgent: z.string().nullable(),
    loggedInAt: z.string(),
    loggedOutAt: z.string().nullable().optional(),
  });
  /** @description 通知設定 */
  export const SettingsNotifications = z.object({
    clockInReminder: z.boolean(),
    leaveReminder: z.boolean(),
  });
  /** @description セキュリティ設定 */
  export const SettingsSecurity = z.object({
    twoFactorEnabled: z.boolean(),
    emailVerified: z.boolean(),
    lastLoginAt: z.string().nullable().optional(),
    passwordLastChangedAt: z.string().nullable().optional(),
  });
  export const TeamMembersResponse = z.object({
    members: z.array(components["schemas"]["TeamMember"]),
  });
  /** @description チームメンバー情報 */
  export const TeamMember = z.object({
    id: z.string(),
    name: z.string(),
    role: z.string(),
    department: z.string(),
    status: components["schemas"]["TeamMemberStatus"],
    clockInTime: z.string().nullable().optional(),
    email: z.string(),
  });
  /** @description エラー発生時のHTTPレスポンス */
  export const ErrorResponse = z.object({
    message: z.string(),
  });
  /** @description バリデーションエラー発生時のHTTPレスポンス */
  export const ValidationErrorResponse = z.object({
    message: z.string(),
    errors: z.record(z.string(), z.array(z.string())),
  });
  /** @description ページネーション情報。一覧系HTTPレスポンスに必ず付与される。 */
  export const PageInfo = z.object({
    currentPage: z.number().int(),
    perPage: z.number().int(),
    totalItems: z.number().int(),
    totalPages: z.number().int(),
  });
}
export namespace components.responses {
  /** @description 認証エラー */
  export const Unauthorized = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description バリデーションエラー */
  export const ValidationError = {
    content: {
      "application/json": components["schemas"]["ValidationErrorResponse"],
    },
  };
  /** @description サーバーエラー */
  export const InternalServerError = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description 排他エラー */
  export const Conflict = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description リソース未存在エラー */
  export const NotFound = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description 認可エラー */
  export const Forbidden = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
}
export namespace components.parameters {
  /** @description 検索期間の開始日 */
  export const QueryDateFrom = z.string();
  /** @description 検索期間の終了日 */
  export const QueryDateTo = z.string();
  /** @description ページ番号（デフォルト1） */
  export const QueryPage = z.number().int();
  /** @description 1ページあたりの件数（デフォルト20） */
  export const QueryPerPage = z.number().int();
  /** @description 勤怠レコードID */
  export const PathAttendanceId = z.string();
  /** @description 対象年 */
  export const QueryYear = z.number().int();
  /** @description 対象月 */
  export const QueryMonth = z.number().int();
}
export namespace components.requestBodies {
  export const LoginBody = {
    content: {
      "application/json": components["schemas"]["LoginRequest"],
    },
  };
  export const AttendanceClockInBody = {
    content: {
      "application/json": components["schemas"]["AttendanceClockInRequest"],
    },
  };
  export const AttendanceClockOutBody = {
    content: {
      "application/json": components["schemas"]["AttendanceClockOutRequest"],
    },
  };
  export const AttendanceBreakStartBody = {
    content: {
      "application/json": components["schemas"]["AttendanceBreakStartRequest"],
    },
  };
  export const AttendanceBreakEndBody = {
    content: {
      "application/json": components["schemas"]["AttendanceBreakEndRequest"],
    },
  };
  export const AttendanceStoreBody = {
    content: {
      "application/json": components["schemas"]["AttendanceStoreRequest"],
    },
  };
  export const AttendanceUpdateBody = {
    content: {
      "application/json": components["schemas"]["AttendanceUpdateRequest"],
    },
  };
  export const SettingsUpdateBody = {
    content: {
      "application/json": components["schemas"]["UpdateSettingsRequest"],
    },
  };
  export const PasswordChangeBody = {
    content: {
      "application/json": components["schemas"]["ChangePasswordRequest"],
    },
  };
}

export const operations = {

  login: {
    /**
     * ログイン 
     * @description メールアドレスとパスワードで認証し、JWTトークンを返す。
     */
    requestBody: components["requestBodies"]["LoginBody"],
    responses: {
      /** @description ログイン成功 */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  logout: {
    /**
     * ログアウト 
     * @description 現在のJWTトークンを無効化する。
     */
    responses: {
      /** @description ログアウト成功 */
      200: {
        content: {
          "application/json": components["schemas"]["LogoutResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getMe: {
    /**
     * ログイン中ユーザー情報取得 
     * @description 現在認証中のユーザー情報を返す。
     */
    responses: {
      /** @description 認証済みユーザー情報 */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getLatestAttendance: {
    /**
     * 最新の勤怠情報取得 
     * @description ログイン中ユーザーの最新の勤怠情報を返す。
     */
    responses: {
      /** @description 最新の勤怠情報 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  createClockIn: {
    /**
     * 出勤打刻 
     * @description 当日の出勤打刻を行う。
     */
    requestBody: components["requestBodies"]["AttendanceClockInBody"],
    responses: {
      /** @description 出勤成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  createClockOut: {
    /**
     * 退勤打刻 
     * @description 当日の退勤打刻を行う。
     */
    requestBody: components["requestBodies"]["AttendanceClockOutBody"],
    responses: {
      /** @description 退勤成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  createBreakStart: {
    /**
     * 休憩開始打刻 
     * @description 勤務中のユーザーが休憩を開始する。
     * サーバー側で現在時刻を休憩開始時刻として記録する。
     * Request Body は空オブジェクト `{}` を送信する。
     */
    requestBody: components["requestBodies"]["AttendanceBreakStartBody"],
    responses: {
      /** @description 休憩開始成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  createBreakEnd: {
    /**
     * 休憩終了打刻 
     * @description 休憩中のユーザーが休憩を終了する。
     * サーバー側で現在時刻を休憩終了時刻として記録する。
     * Request Body は空オブジェクト `{}` を送信する。
     */
    requestBody: components["requestBodies"]["AttendanceBreakEndBody"],
    responses: {
      /** @description 休憩終了成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  listAttendances: {
    /**
     * 勤怠一覧取得 
     * @description 指定期間のログインユーザー勤怠一覧をページネーション付きで返す。
     */
    responses: {
      /** @description 勤怠一覧 */
      200: {
        content: {
          "application/json": z.object({
            items: z.array(components["schemas"]["AttendanceResponse"]),
            pageInfo: components["schemas"]["PageInfo"],
          }),
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  createAttendance: {
    /**
     * 勤怠の新規登録 
     * @description 勤怠レコードを新規作成する。
     */
    requestBody: components["requestBodies"]["AttendanceStoreBody"],
    responses: {
      /** @description 登録成功 */
      201: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  updateAttendance: {
    /**
     * 勤怠の更新 
     * @description 勤怠レコードを更新する。
     */
    requestBody: components["requestBodies"]["AttendanceUpdateBody"],
    responses: {
      /** @description 更新成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      404: components["responses"]["NotFound"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getDashboard: {
    /**
     * ダッシュボード集計取得 
     * @description 当月の勤怠統計・今日の勤怠・直近の勤怠記録をまとめて返す。
     */
    responses: {
      /** @description ダッシュボード情報 */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getCalendar: {
    /**
     * 月次カレンダー取得 
     * @description 指定年月のカレンダー日付一覧とサマリーを返す。
     */
    responses: {
      /** @description 対象月の日付一覧 */
      200: {
        content: {
          "application/json": components["schemas"]["CalendarResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  listTeamMembers: {
    /**
     * チームメンバー一覧取得 
     * @description ログインユーザーが所属するチームのメンバー一覧を返す。
     */
    responses: {
      /** @description チームメンバー一覧 */
      200: {
        content: {
          "application/json": components["schemas"]["TeamMembersResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getSettings: {
    /**
     * ユーザー設定取得 
     * @description ログインユーザーのプロフィール・通知・セキュリティ設定を返す。
     */
    responses: {
      /** @description ユーザー設定 */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  updateSettings: {
    /**
     * ユーザー設定更新 
     * @description プロフィール・通知・テーマ・言語設定を更新する。
     */
    requestBody: components["requestBodies"]["SettingsUpdateBody"],
    responses: {
      /** @description 更新後ユーザー設定 */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  updatePassword: {
    /**
     * パスワード変更 
     * @description 現在のパスワードを検証し、新しいパスワードに変更する。
     */
    requestBody: components["requestBodies"]["PasswordChangeBody"],
    responses: {
      /** @description パスワード変更成功 */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  listLoginHistories: {
    /**
     * ログイン履歴一覧取得 
     * @description ログインユーザーのログイン履歴を新しい順に返す。
     */
    responses: {
      /** @description ログイン履歴一覧 */
      200: {
        content: {
          "application/json": z.object({
            items: z.array(components["schemas"]["LoginHistoryResponse"]),
            pageInfo: components["schemas"]["PageInfo"],
          }),
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
}

export const paths = {
  "/login": {
    /**
     * ログイン 
     * @description メールアドレスとパスワードで認証し、JWTトークンを返す。
     */
    post: operations["login"],
  },
  "/logout": {
    /**
     * ログアウト 
     * @description 現在のJWTトークンを無効化する。
     */
    post: operations["logout"],
  },
  "/auth/me": {
    /**
     * ログイン中ユーザー情報取得 
     * @description 現在認証中のユーザー情報を返す。
     */
    get: operations["getMe"],
  },
  "/attendances/latest": {
    /**
     * 最新の勤怠情報取得 
     * @description ログイン中ユーザーの最新の勤怠情報を返す。
     */
    get: operations["getLatestAttendance"],
  },
  "/attendances/clock-in": {
    /**
     * 出勤打刻 
     * @description 当日の出勤打刻を行う。
     */
    post: operations["createClockIn"],
  },
  "/attendances/clock-out": {
    /**
     * 退勤打刻 
     * @description 当日の退勤打刻を行う。
     */
    post: operations["createClockOut"],
  },
  "/attendances/break-start": {
    /**
     * 休憩開始打刻 
     * @description 勤務中のユーザーが休憩を開始する。
     * サーバー側で現在時刻を休憩開始時刻として記録する。
     * Request Body は空オブジェクト `{}` を送信する。
     */
    post: operations["createBreakStart"],
  },
  "/attendances/break-end": {
    /**
     * 休憩終了打刻 
     * @description 休憩中のユーザーが休憩を終了する。
     * サーバー側で現在時刻を休憩終了時刻として記録する。
     * Request Body は空オブジェクト `{}` を送信する。
     */
    post: operations["createBreakEnd"],
  },
  "/attendances": {
    /**
     * 勤怠一覧取得 
     * @description 指定期間のログインユーザー勤怠一覧をページネーション付きで返す。
     */
    get: operations["listAttendances"],
    /**
     * 勤怠の新規登録 
     * @description 勤怠レコードを新規作成する。
     */
    post: operations["createAttendance"],
  },
  "/attendances/{attendanceId}": {
    /**
     * 勤怠の更新 
     * @description 勤怠レコードを更新する。
     */
    patch: operations["updateAttendance"],
  },
  "/dashboard": {
    /**
     * ダッシュボード集計取得 
     * @description 当月の勤怠統計・今日の勤怠・直近の勤怠記録をまとめて返す。
     */
    get: operations["getDashboard"],
  },
  "/schedule/calendar": {
    /**
     * 月次カレンダー取得 
     * @description 指定年月のカレンダー日付一覧とサマリーを返す。
     */
    get: operations["getCalendar"],
  },
  "/team/members": {
    /**
     * チームメンバー一覧取得 
     * @description ログインユーザーが所属するチームのメンバー一覧を返す。
     */
    get: operations["listTeamMembers"],
  },
  "/settings": {
    /**
     * ユーザー設定取得 
     * @description ログインユーザーのプロフィール・通知・セキュリティ設定を返す。
     */
    get: operations["getSettings"],
    /**
     * ユーザー設定更新 
     * @description プロフィール・通知・テーマ・言語設定を更新する。
     */
    put: operations["updateSettings"],
  },
  "/settings/password": {
    /**
     * パスワード変更 
     * @description 現在のパスワードを検証し、新しいパスワードに変更する。
     */
    put: operations["updatePassword"],
  },
  "/settings/login-histories": {
    /**
     * ログイン履歴一覧取得 
     * @description ログインユーザーのログイン履歴を新しい順に返す。
     */
    get: operations["listLoginHistories"],
  },
}
