/**
 * This file was auto-generated by openapi-zod.
 * Do not make direct changes to the file.
 */


import { z } from 'zod';

export namespace components.schemas {
  export const CalendarIndexRequest = z.object({
    year: z.number().int(),
    month: z.number().int(),
  });
  export const AttendanceIndexRequest = z.object({
    from: z.string(),
    to: z.string(),
  });
  export const LoginRequest = z.object({
    email: z.string(),
    password: z.string(),
  });
  export const LoginResponse = z.object({
    token: z.string().optional(),
  });
  export const ErrorResponse = z.object({
    message: z.string().optional(),
  });
  export const ValidationErrorResponse = z.object({
    message: z.string().optional(),
    errors: z.record(z.string(), z.array(z.string())).optional(),
  });
  /** @description ユーザー情報 */
  export const UserResponse = z.object({
    user: z.object({
      id: z.string(),
      name: z.string(),
      email: z.string(),
      roles: z.array(z.string()),
      settings: z.record(z.string(), z.unknown()).nullable().optional(),
    }),
  });
  export const AttendanceResponse = z.object({
    user_id: z.string(),
    work_date: z.string(),
    start_time: z.string().nullable(),
    end_time: z.string().nullable().optional(),
  });
  export const AttendanceClockInRequest = z.object({
    work_date: z.string(),
    start_time: z.string(),
  });
  export const AttendanceClockOutRequest = z.object({
    work_date: z.string(),
    end_time: z.string(),
  });
  export const AttendanceStoreRequest = z.object({
    work_date: z.string(),
    start_time: z.string(),
    end_time: z.string().nullable().optional(),
    note: z.string().nullable().optional(),
  });
  export const AttendanceUpdateRequest = z.object({
    start_time: z.string().nullable().optional(),
    end_time: z.string().nullable().optional(),
    note: z.string().nullable().optional(),
  });
  export const DashboardResponse = z.object({
    user: z.object({
      id: z.string(),
      name: z.string(),
    }),
    clockStatus: z.enum(["out", "in", "break"]),
    todayRecord: z.object({
      clockInTime: z.string().nullable(),
      totalWorkedHours: z.number().nullable(),
    }),
    stats: z.object({
      totalHours: z.number(),
      targetHours: z.number(),
      workDays: z.number().int(),
      remainingDays: z.number().int(),
      avgHours: z.number(),
      avgHoursDiff: z.number(),
      overtimeHours: z.number(),
      overtimeDiff: z.number(),
    }),
    recentRecords: z.array(z.object({
        date: z.string(),
        day: z.string(),
        clockIn: z.string().nullable(),
        clockOut: z.string().nullable(),
        workHours: z.number().nullable(),
        status: z.enum(["通常", "残業", "休日"]),
      })),
    pendingOvertimeRequests: z.number().int(),
  });
  export const DashboardClockRequest = z.object({
    action: z.enum(["in", "out", "break_start", "break_end"]),
  });
  export const CalendarSummary = z.object({
    totalWorkHours: z.number(),
    targetHours: z.number(),
    scheduledWorkDays: z.number().int(),
    overtimeHours: z.number(),
    paidLeaveDays: z.number(),
    remainingPaidLeaveDays: z.number(),
  });
  export const CalendarDay = z.object({
    date: z.string(),
    label: z.string(),
    dayOfWeek: z.string(),
    status: z.enum(["working", "off", "holiday", "pending"]),
    shift: z.string().nullable().optional(),
    timeRange: z.string().nullable().optional(),
    location: z.string().nullable().optional(),
    note: z.string().nullable().optional(),
    isToday: z.boolean(),
    isHoliday: z.boolean(),
  });
  export const CalendarResponse = z.object({
    year: z.number().int(),
    month: z.number().int(),
    summary: components["schemas"]["CalendarSummary"],
    days: z.array(components["schemas"]["CalendarDay"]),
  });
  export const TeamMember = z.object({
    id: z.string(),
    name: z.string(),
    role: z.string(),
    department: z.string(),
    status: z.enum(["working", "break", "off", "leave"]),
    clockInTime: z.string().nullable().optional(),
    email: z.string(),
  });
  export const TeamMembersResponse = z.object({
    members: z.array(components["schemas"]["TeamMember"]),
  });
  export const SettingsResponse = z.object({
    profile: z.object({
      name: z.string(),
      email: z.string(),
      department: z.string(),
      role: z.string(),
      employeeCode: z.string(),
    }),
    notifications: z.object({
      clockInReminder: z.boolean(),
      approvalNotification: z.boolean(),
      leaveReminder: z.boolean(),
    }),
    security: z.object({
      twoFactorEnabled: z.boolean(),
      emailVerified: z.boolean(),
      lastLoginAt: z.string().nullable().optional(),
      passwordLastChangedAt: z.string().nullable().optional(),
    }),
    theme: z.enum(["light", "dark"]),
    language: z.enum(["ja", "en"]),
  });
  export const UpdateSettingsRequest = z.object({
    profile: z.object({
      name: z.string(),
      email: z.string(),
    }),
    notifications: z.object({
      clockInReminder: z.boolean(),
      approvalNotification: z.boolean(),
      leaveReminder: z.boolean(),
    }),
    theme: z.enum(["light", "dark"]),
    language: z.enum(["ja", "en"]),
  });
}
export namespace components.responses {
  /** @description 認証エラー */
  export const Unauthorized = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description バリデーションエラー */
  export const ValidationError = {
    content: {
      "application/json": components["schemas"]["ValidationErrorResponse"],
    },
  };
  /** @description サーバーエラー */
  export const InternalServerError = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description 排他エラー */
  export const Conflict = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description リソース未存在エラー */
  export const NotFound = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description 認可エラー */
  export const Forbidden = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
}

export const operations = {

  loginApi: {
    /** ログイン */
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"],
      },
    },
    responses: {
      /** @description ログイン成功 */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  logoutApi: {
    /** ログアウト */
    responses: {
      /** @description ログアウト成功 */
      200: {
        content: {
          "application/json": z.object({
            message: z.string().optional(),
          }),
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  authMeApi: {
    /** ログイン中ユーザー情報取得 */
    responses: {
      /** @description 認証済みユーザー情報 */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  todayAttendanceApi: {
    /** 今日の勤怠取得 */
    responses: {
      /** @description 今日の勤怠情報 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  clockInApi: {
    /** 出勤打刻 */
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttendanceClockInRequest"],
      },
    },
    responses: {
      /** @description 出勤成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  clockOutApi: {
    /** 退勤打刻 */
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttendanceClockOutRequest"],
      },
    },
    responses: {
      /** @description 退勤成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  listAttendancesApi: {
    /** 勤怠一覧取得 */
    parameters: {
      query: z.object({
        from: z.string(),
        to: z.string(),
      }),
    },
    responses: {
      /** @description 勤怠一覧 */
      200: {
        content: {
          "application/json": z.array(components["schemas"]["AttendanceResponse"]),
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  storeAttendanceApi: {
    /** 勤怠の新規登録 */
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttendanceStoreRequest"],
      },
    },
    responses: {
      /** @description 登録成功 */
      201: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  updateAttendanceApi: {
    /** 勤怠の更新 */
    parameters: {
      path: z.object({
        attendance: z.string(),
      }),
    },
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttendanceUpdateRequest"],
      },
    },
    responses: {
      /** @description 更新成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      404: components["responses"]["NotFound"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getDashboardApi: {
    /** ダッシュボード集計取得 */
    responses: {
      /** @description ダッシュボード情報 */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  dashboardClockApi: {
    /** 打刻アクション（出勤・退勤・休憩開始・休憩終了） */
    requestBody: {
      content: {
        "application/json": components["schemas"]["DashboardClockRequest"],
      },
    },
    responses: {
      /** @description 打刻成功 */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getCalendarApi: {
    /** 月次カレンダー取得 */
    parameters: {
      query: z.object({
        year: z.number().int(),
        month: z.number().int(),
      }),
    },
    responses: {
      /** @description 対象月の日付一覧 */
      200: {
        content: {
          "application/json": components["schemas"]["CalendarResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getTeamMembersApi: {
    /** チームメンバー一覧取得 */
    responses: {
      /** @description チームメンバー一覧 */
      200: {
        content: {
          "application/json": components["schemas"]["TeamMembersResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getSettingsApi: {
    /** ユーザー設定取得 */
    responses: {
      /** @description ユーザー設定 */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  updateSettingsApi: {
    /** ユーザー設定更新 */
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateSettingsRequest"],
      },
    },
    responses: {
      /** @description 更新後ユーザー設定 */
      200: {
        content: {
          "application/json": components["schemas"]["SettingsResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
}

export const paths = {
  "/login": {
    /** ログイン */
    post: operations["loginApi"],
  },
  "/logout": {
    /** ログアウト */
    post: operations["logoutApi"],
  },
  "/authme": {
    /** ログイン中ユーザー情報取得 */
    get: operations["authMeApi"],
  },
  "/attendances/attendance": {
    /** 今日の勤怠取得 */
    get: operations["todayAttendanceApi"],
  },
  "/attendances/clock-in": {
    /** 出勤打刻 */
    post: operations["clockInApi"],
  },
  "/attendances/clock-out": {
    /** 退勤打刻 */
    post: operations["clockOutApi"],
  },
  "/attendances": {
    /** 勤怠一覧取得 */
    get: operations["listAttendancesApi"],
    /** 勤怠の新規登録 */
    post: operations["storeAttendanceApi"],
  },
  "/attendances/{attendance}": {
    /** 勤怠の更新 */
    patch: operations["updateAttendanceApi"],
  },
  "/dashboard": {
    /** ダッシュボード集計取得 */
    get: operations["getDashboardApi"],
  },
  "/dashboard/clock": {
    /** 打刻アクション（出勤・退勤・休憩開始・休憩終了） */
    post: operations["dashboardClockApi"],
  },
  "/auth/calendar": {
    /** 月次カレンダー取得 */
    get: operations["getCalendarApi"],
  },
  "/team/members": {
    /** チームメンバー一覧取得 */
    get: operations["getTeamMembersApi"],
  },
  "/settings": {
    /** ユーザー設定取得 */
    get: operations["getSettingsApi"],
    /** ユーザー設定更新 */
    put: operations["updateSettingsApi"],
  },
}
