SettingsNotifications:
  type: object
  description: 通知設定
  required:
    - clockInReminder
    - leaveReminder
  properties:
    clockInReminder:
      type: boolean
    leaveReminder:
      type: boolean
