SettingsResponse:
  type: object
  required:
    - profile
    - notifications
    - security
    - theme
    - language
  properties:
    profile:
      $ref: "./SettingsProfile.yaml#/SettingsProfile"
    notifications:
      $ref: "./SettingsNotifications.yaml#/SettingsNotifications"
    security:
      $ref: "./SettingsSecurity.yaml#/SettingsSecurity"
    theme:
      $ref: "../../enums/ThemeType.yaml#/ThemeType"
    language:
      $ref: "../../enums/LanguageCode.yaml#/LanguageCode"
