UpdateSettingsRequest:
  type: object
  required:
    - profile
    - notifications
    - theme
    - language
  properties:
    profile:
      $ref: "./UpdateSettingsProfile.yaml#/UpdateSettingsProfile"
    notifications:
      $ref: "./SettingsNotifications.yaml#/SettingsNotifications"
    theme:
      $ref: "../../enums/ThemeType.yaml#/ThemeType"
    language:
      $ref: "../../enums/LanguageCode.yaml#/LanguageCode"
