/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Attendance API
 * 勤怠管理API（JWT認証）
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";
import type {
  LoginRequest,
  LoginResponse,
  ServerErrorResponse,
  UnauthorizedResponse,
  ValidationErrorResponse,
} from "@/api/__generated__/model";
import { customInstance } from "@/api/client";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * @summary ログイン
 */
export const loginApi = (loginRequest: LoginRequest) => {
  return customInstance<LoginResponse>({
    url: `/login`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: loginRequest,
  });
};

export const getLoginApiMutationOptions = <
  TError = UnauthorizedResponse | ValidationErrorResponse | ServerErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginApi>>,
    TError,
    { data: LoginRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginApi>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const { mutation: mutationOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginApi>>,
    { data: LoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return loginApi(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginApiMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginApi>>
>;
export type LoginApiMutationBody = LoginRequest;
export type LoginApiMutationError =
  | UnauthorizedResponse
  | ValidationErrorResponse
  | ServerErrorResponse;

/**
 * @summary ログイン
 */
export const useLoginApi = <
  TError = UnauthorizedResponse | ValidationErrorResponse | ServerErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginApi>>,
    TError,
    { data: LoginRequest },
    TContext
  >;
}): UseMutationResult<
  Awaited<ReturnType<typeof loginApi>>,
  TError,
  { data: LoginRequest },
  TContext
> => {
  const mutationOptions = getLoginApiMutationOptions(options);

  return useMutation(mutationOptions);
};
