/**
 * This file was auto-generated by openapi-zod.
 * Do not make direct changes to the file.
 */


import { z } from 'zod';

export namespace components.schemas {
  export const LoginRequest = z.object({
    email: z.string(),
    password: z.string(),
  });
  export const LoginResponse = z.object({
    token: z.string().optional(),
  });
  export const ErrorResponse = z.object({
    message: z.string().optional(),
  });
  export const ValidationErrorResponse = z.object({
    message: z.string().optional(),
    errors: z.record(z.string(), z.array(z.string())).optional(),
  });
  export const Attendance = z.object({
    id: z.string(),
    user_id: z.string(),
    work_date: z.string(),
    start_time: z.string().nullable(),
    end_time: z.string().nullable().optional(),
    created_at: z.string().optional(),
    updated_at: z.string().optional(),
  });
}
export namespace components.responses {
  /** @description 認証エラー */
  export const Unauthorized = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description バリデーションエラー */
  export const ValidationError = {
    content: {
      "application/json": components["schemas"]["ValidationErrorResponse"],
    },
  };
  /** @description サーバーエラー */
  export const ServerError = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description 業務競合エラー（重複打刻など） */
  export const Conflict = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
}

export const operations = {

  loginApi: {
    /** ログイン */
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"],
      },
    },
    responses: {
      /** @description JWTトークン */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["ServerError"],
    },
  },
  todayApi: {
    /** 今日の勤怠取得 */
    responses: {
      /** @description 今日の勤怠情報 */
      200: {
        content: {
          "application/json": components["schemas"]["Attendance"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["ServerError"],
    },
  },
  clockInApi: {
    /** 出勤打刻 */
    responses: {
      /** @description 出勤成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Attendance"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["ServerError"],
    },
  },
  clockOutApi: {
    /** 退勤打刻 */
    responses: {
      /** @description 退勤成功 */
      200: {
        content: {
          "application/json": components["schemas"]["Attendance"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["ServerError"],
    },
  },
}

export const paths = {
  "/login": {
    /** ログイン */
    post: operations["loginApi"],
  },
  "/attendances/today": {
    /** 今日の勤怠取得 */
    get: operations["todayApi"],
  },
  "/attendances/clock-in": {
    /** 出勤打刻 */
    post: operations["clockInApi"],
  },
  "/attendances/clock-out": {
    /** 退勤打刻 */
    post: operations["clockOutApi"],
  },
}
