/**
 * This file was auto-generated by openapi-zod.
 * Do not make direct changes to the file.
 */


import { z } from 'zod';

export namespace components.schemas {
  export const LoginRequest = z.object({
    email: z.string(),
    password: z.string(),
  });
  export const LoginResponse = z.object({
    token: z.string().optional(),
  });
  export const ErrorResponse = z.object({
    message: z.string().optional(),
  });
  export const ValidationErrorResponse = z.object({
    message: z.string().optional(),
    errors: z.record(z.array(z.string())).optional(),
  });
  /** @description ユーザー情報 */
  export const UserResponse = z.object({
    user: z.object({
      id: z.string(),
      name: z.string(),
      email: z.string(),
      roles: z.array(z.string()),
      settings: z.record(z.unknown()).nullable().optional(),
    }),
  });
  export const AttendanceResponse = z.object({
    user_id: z.string(),
    work_date: z.string(),
    start_time: z.string().nullable(),
    end_time: z.string().nullable().optional(),
  });
  export const AttendanceClockInRequest = z.object({
    work_date: z.string(),
    start_time: z.string(),
  });
  export const AttendanceClockOutRequest = z.object({
    end_time: z.string(),
  });
  export const DashboardResponse = z.object({
    user: z.object({
      id: z.string(),
      name: z.string(),
    }),
    clockStatus: z.enum(["out", "in", "break"]),
    todayRecord: z.object({
      clockInTime: z.string().nullable(),
      totalWorkedHours: z.number().nullable(),
    }),
    stats: z.object({
      totalHours: z.number(),
      targetHours: z.number(),
      workDays: z.number().int(),
      remainingDays: z.number().int(),
      avgHours: z.number(),
      avgHoursDiff: z.number(),
      overtimeHours: z.number(),
      overtimeDiff: z.number(),
    }),
    recentRecords: z.array(z.object({
        date: z.string(),
        day: z.string(),
        clockIn: z.string().nullable(),
        clockOut: z.string().nullable(),
        workHours: z.number().nullable(),
        status: z.enum(["通常", "残業", "休日"]),
      })),
    pendingOvertimeRequests: z.number().int(),
  });
  export const DashboardClockRequest = z.object({
    action: z.enum(["in", "out", "break_start", "break_end"]),
  });
  export const DashboardClockResponse = z.object({
    action: z.enum(["in", "out", "break_start", "break_end"]),
    timestamp: z.string(),
    dashboard: components["schemas"]["DashboardResponse"],
  });
}
export namespace components.responses {
  /** @description 認証エラー */
  export const Unauthorized = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description バリデーションエラー */
  export const ValidationError = {
    content: {
      "application/json": components["schemas"]["ValidationErrorResponse"],
    },
  };
  /** @description サーバーエラー */
  export const InternalServerError = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description 排他エラー */
  export const Conflict = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description 認可エラー */
  export const Forbidden = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
  /** @description リソース未存在エラー */
  export const NotFound = {
    content: {
      "application/json": components["schemas"]["ErrorResponse"],
    },
  };
}

export const operations = {

  loginApi: {
    /** ログイン */
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"],
      },
    },
    responses: {
      /** @description ログイン成功 */
      200: {
        content: {
          "application/json": components["schemas"]["LoginResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  logoutApi: {
    /** ログアウト */
    responses: {
      /** @description ログアウト成功 */
      200: {
        content: {
          "application/json": z.object({
            message: z.string().optional(),
          }),
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  authMeApi: {
    /** ログイン中ユーザー情報取得 */
    responses: {
      /** @description 認証済みユーザー情報 */
      200: {
        content: {
          "application/json": components["schemas"]["UserResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  todayAttendanceApi: {
    /** 今日の勤怠取得 */
    responses: {
      /** @description 今日の勤怠情報 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  clockInApi: {
    /** 出勤打刻 */
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttendanceClockInRequest"],
      },
    },
    responses: {
      /** @description 出勤成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  clockOutApi: {
    /** 退勤打刻 */
    requestBody: {
      content: {
        "application/json": components["schemas"]["AttendanceClockOutRequest"],
      },
    },
    responses: {
      /** @description 退勤成功 */
      200: {
        content: {
          "application/json": components["schemas"]["AttendanceResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
  getDashboardApi: {
    /** ダッシュボード集計取得 */
    responses: {
      /** @description ダッシュボード情報 */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      500: components["responses"]["InternalServerError"],
    },
  },
  postDashboardClockApi: {
    /** ダッシュボード打刻操作 */
    requestBody: {
      content: {
        "application/json": components["schemas"]["DashboardClockRequest"],
      },
    },
    responses: {
      /** @description 打刻成功 */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardClockResponse"],
        },
      },
      401: components["responses"]["Unauthorized"],
      409: components["responses"]["Conflict"],
      422: components["responses"]["ValidationError"],
      500: components["responses"]["InternalServerError"],
    },
  },
}

export const paths = {
  "/login": {
    /** ログイン */
    post: operations["loginApi"],
  },
  "/logout": {
    /** ログアウト */
    post: operations["logoutApi"],
  },
  "/authme": {
    /** ログイン中ユーザー情報取得 */
    get: operations["authMeApi"],
  },
  "/attendances/attendance": {
    /** 今日の勤怠取得 */
    get: operations["todayAttendanceApi"],
  },
  "/attendances/clock-in": {
    /** 出勤打刻 */
    post: operations["clockInApi"],
  },
  "/attendances/clock-out": {
    /** 退勤打刻 */
    post: operations["clockOutApi"],
  },
  "/dashboard": {
    /** ダッシュボード集計取得 */
    get: operations["getDashboardApi"],
  },
  "/dashboard/clock": {
    /** ダッシュボード打刻操作 */
    post: operations["postDashboardClockApi"],
  },
}
