/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理システムの REST API 定義。
従業員の出退勤・休憩管理、
ダッシュボード集計、カレンダー、ユーザー設定を提供する。

## 認証
JWT Bearer トークンを `Authorization: Bearer <token>` ヘッダーで送信する。
`/login` のみ認証不要。それ以外は全て認証必須。

## エラーハンドリング
- 401: トークン無効または期限切れ
- 403: 権限不足
- 404: 指定リソースが存在しない
- 409: 状態の競合（二重打刻など）
- 422: バリデーションエラー（フィールド別メッセージ付き）
- 500: 予期しないサーバーエラー

 * OpenAPI spec version: 1.1.0
 */
import type {
  AttendanceBreakEndBodyBody,
  AttendanceBreakStartBodyBody,
  AttendanceClockInBodyBody,
  AttendanceClockOutBodyBody,
  AttendanceResponse,
  AttendanceStoreBodyBody,
  AttendanceUpdateBodyBody,
  ListAttendances200,
  ListAttendancesParams,
} from ".././model";
import { customInstance } from "../../lib/http/client";

export const getAttendance = () => {
  /**
   * ログイン中ユーザーの当日の勤怠レコードを返す。
   * @summary 今日の勤怠取得
   */
  const getTodayAttendance = () => {
    return customInstance<AttendanceResponse>({
      url: `/attendances/today`,
      method: "GET",
    });
  };
  /**
   * 当日の出勤打刻を行う。
   * @summary 出勤打刻
   */
  const createClockIn = (
    attendanceClockInBodyBody: AttendanceClockInBodyBody,
  ) => {
    return customInstance<AttendanceResponse>({
      url: `/attendances/clock-in`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: attendanceClockInBodyBody,
    });
  };
  /**
   * 当日の退勤打刻を行う。
   * @summary 退勤打刻
   */
  const createClockOut = (
    attendanceClockOutBodyBody: AttendanceClockOutBodyBody,
  ) => {
    return customInstance<AttendanceResponse>({
      url: `/attendances/clock-out`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: attendanceClockOutBodyBody,
    });
  };
  /**
 * 勤務中のユーザーが休憩を開始する。
サーバー側で現在時刻を休憩開始時刻として記録する。
Request Body は空オブジェクト `{}` を送信する。

 * @summary 休憩開始打刻
 */
  const createBreakStart = (
    attendanceBreakStartBodyBody: AttendanceBreakStartBodyBody,
  ) => {
    return customInstance<AttendanceResponse>({
      url: `/attendances/break-start`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: attendanceBreakStartBodyBody,
    });
  };
  /**
 * 休憩中のユーザーが休憩を終了する。
サーバー側で現在時刻を休憩終了時刻として記録する。
Request Body は空オブジェクト `{}` を送信する。

 * @summary 休憩終了打刻
 */
  const createBreakEnd = (
    attendanceBreakEndBodyBody: AttendanceBreakEndBodyBody,
  ) => {
    return customInstance<AttendanceResponse>({
      url: `/attendances/break-end`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: attendanceBreakEndBodyBody,
    });
  };
  /**
   * 指定期間のログインユーザー勤怠一覧をページネーション付きで返す。
   * @summary 勤怠一覧取得
   */
  const listAttendances = (params: ListAttendancesParams) => {
    return customInstance<ListAttendances200>({
      url: `/attendances`,
      method: "GET",
      params,
    });
  };
  /**
   * 勤怠レコードを新規作成する。
   * @summary 勤怠の新規登録
   */
  const createAttendance = (
    attendanceStoreBodyBody: AttendanceStoreBodyBody,
  ) => {
    return customInstance<AttendanceResponse>({
      url: `/attendances`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: attendanceStoreBodyBody,
    });
  };
  /**
   * 勤怠レコードを更新する。
   * @summary 勤怠の更新
   */
  const updateAttendance = (
    attendanceId: string,
    attendanceUpdateBodyBody: AttendanceUpdateBodyBody,
  ) => {
    return customInstance<AttendanceResponse>({
      url: `/attendances/${attendanceId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: attendanceUpdateBodyBody,
    });
  };
  return {
    getTodayAttendance,
    createClockIn,
    createClockOut,
    createBreakStart,
    createBreakEnd,
    listAttendances,
    createAttendance,
    updateAttendance,
  };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetTodayAttendanceResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["getTodayAttendance"]>>
>;
export type CreateClockInResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["createClockIn"]>>
>;
export type CreateClockOutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["createClockOut"]>>
>;
export type CreateBreakStartResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["createBreakStart"]>>
>;
export type CreateBreakEndResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["createBreakEnd"]>>
>;
export type ListAttendancesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["listAttendances"]>>
>;
export type CreateAttendanceResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["createAttendance"]>>
>;
export type UpdateAttendanceResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["updateAttendance"]>>
>;
