/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type {
  AttendanceClockInBodyBody,
  AttendanceClockOutBodyBody,
  AttendanceResponse,
  AttendanceStoreBodyBody,
  AttendanceUpdateBodyBody,
  ListAttendances200,
  ListAttendancesParams,
} from ".././model";
import { customInstance } from "../../lib/http/client";

export const getAttendance = () => {
  /**
   * ログイン中ユーザーの当日の勤怠レコードを返す。
   * @summary 今日の勤怠取得
   */
  const getTodayAttendance = () => {
    return customInstance<AttendanceResponse>({
      url: `/attendances/today`,
      method: "GET",
    });
  };
  /**
   * 当日の出勤打刻を行う。既に出勤済みの場合は 409 を返す。
   * @summary 出勤打刻
   */
  const createClockIn = (
    attendanceClockInBodyBody: AttendanceClockInBodyBody,
  ) => {
    return customInstance<AttendanceResponse>({
      url: `/attendances/clock-in`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: attendanceClockInBodyBody,
    });
  };
  /**
   * 当日の退勤打刻を行う。未出勤の場合は 409 を返す。
   * @summary 退勤打刻
   */
  const createClockOut = (
    attendanceClockOutBodyBody: AttendanceClockOutBodyBody,
  ) => {
    return customInstance<AttendanceResponse>({
      url: `/attendances/clock-out`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: attendanceClockOutBodyBody,
    });
  };
  /**
   * 指定期間のログインユーザー勤怠一覧をページネーション付きで返す。
   * @summary 勤怠一覧取得
   */
  const listAttendances = (params: ListAttendancesParams) => {
    return customInstance<ListAttendances200>({
      url: `/attendances`,
      method: "GET",
      params,
    });
  };
  /**
   * 手動で勤怠レコードを新規作成する。
   * @summary 勤怠の新規登録
   */
  const createAttendance = (
    attendanceStoreBodyBody: AttendanceStoreBodyBody,
  ) => {
    return customInstance<AttendanceResponse>({
      url: `/attendances`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: attendanceStoreBodyBody,
    });
  };
  /**
   * 既存の勤怠レコードを部分更新する。
   * @summary 勤怠の更新
   */
  const updateAttendance = (
    attendanceId: string,
    attendanceUpdateBodyBody: AttendanceUpdateBodyBody,
  ) => {
    return customInstance<AttendanceResponse>({
      url: `/attendances/${attendanceId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: attendanceUpdateBodyBody,
    });
  };
  return {
    getTodayAttendance,
    createClockIn,
    createClockOut,
    listAttendances,
    createAttendance,
    updateAttendance,
  };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetTodayAttendanceResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["getTodayAttendance"]>>
>;
export type CreateClockInResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["createClockIn"]>>
>;
export type CreateClockOutResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["createClockOut"]>>
>;
export type ListAttendancesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["listAttendances"]>>
>;
export type CreateAttendanceResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["createAttendance"]>>
>;
export type UpdateAttendanceResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAttendance>["updateAttendance"]>>
>;
