/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Attendance API
 * 勤怠管理API（JWT認証）
 * OpenAPI spec version: 1.0.0
 */

export interface Attendance {
  created_at?: string;
  /** @nullable */
  end_time?: string | null;
  id: string;
  /** @nullable */
  start_time: string | null;
  updated_at?: string;
  user_id: string;
  work_date: string;
}
