/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Attendance API
 * 勤怠管理API（JWT認証）
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationErrorResponseErrors } from './validationErrorResponseErrors';

export interface ValidationErrorResponse {
  errors?: ValidationErrorResponseErrors;
  message?: string;
}
