/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理システムの REST API 定義。
従業員の出退勤・休憩管理、有給休暇・残業の申請承認、
ダッシュボード集計、カレンダー、ユーザー設定を提供する。

## 認証
JWT Bearer トークンを `Authorization: Bearer <token>` ヘッダーで送信する。
`/login` のみ認証不要。それ以外は全て認証必須。

## エラーハンドリング
- 401: トークン無効または期限切れ
- 403: 権限不足（承認権限が必要な操作）
- 404: 指定リソースが存在しない
- 409: 状態の競合（二重打刻など）
- 422: バリデーションエラー（フィールド別メッセージ付き）
- 500: 予期しないサーバーエラー

 * OpenAPI spec version: 1.1.0
 */
import type { CalendarResponse, GetCalendarParams } from ".././model";
import { customInstance } from "../../lib/http/client";

export const getSchedule = () => {
  /**
   * 指定年月のカレンダー日付一覧とサマリーを返す。
   * @summary 月次カレンダー取得
   */
  const getCalendar = (params: GetCalendarParams) => {
    return customInstance<CalendarResponse>({
      url: `/schedule/calendar`,
      method: "GET",
      params,
    });
  };
  return { getCalendar };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetCalendarResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSchedule>["getCalendar"]>>
>;
