/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { CalendarResponse, GetCalendarApiParams } from ".././model";
import { customInstance } from "../../lib/http/client";

export const getSchedule = () => {
  /**
   * @summary 月次カレンダー取得
   */
  const getCalendarApi = (params: GetCalendarApiParams) => {
    return customInstance<CalendarResponse>({
      url: `/auth/calendar`,
      method: "GET",
      params,
    });
  };
  return { getCalendarApi };
};

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

export type GetCalendarApiResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSchedule>["getCalendarApi"]>>
>;
