/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 申請のステータス
 */
export type ApprovalStatus =
  (typeof ApprovalStatus)[keyof typeof ApprovalStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ApprovalStatus = {
  pending: "pending",
  approved: "approved",
  rejected: "rejected",
  canceled: "canceled",
} as const;
