/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { OvertimeRequestResponse } from "./overtimeRequestResponse";
import type { PaidLeaveRequestResponse } from "./paidLeaveRequestResponse";
import type { PaidLeaveSummary } from "./paidLeaveSummary";

export interface ApprovalListResponse {
  /** 現在ユーザーが承認権限を持つか */
  isApprover: boolean;
  /** 自分の残業申請一覧 */
  overtimeRequests: OvertimeRequestResponse[];
  /** 自分の有給休暇申請一覧 */
  paidLeaveRequests: PaidLeaveRequestResponse[];
  paidLeaveSummary: PaidLeaveSummary;
  /** 承認待ち残業申請（承認者のみ） */
  pendingOvertimeRequests: OvertimeRequestResponse[];
  /** 承認待ち有給申請（承認者のみ） */
  pendingPaidLeaveRequests: PaidLeaveRequestResponse[];
}
