/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { ClockStatus } from "./clockStatus";

export interface AttendanceResponse {
  /**
   * 休憩合計(分)
   * @nullable
   */
  breakMinutes?: number | null;
  clockStatus: ClockStatus;
  /** @nullable */
  endTime?: string | null;
  /** @nullable */
  startTime: string | null;
  userId: string;
  workDate: string;
  /**
   * 実働時間(分)
   * @nullable
   */
  workedMinutes?: number | null;
}
