/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理システムの REST API 定義。
従業員の出退勤・休憩管理、
ダッシュボード集計、カレンダー、ユーザー設定を提供する。

## 認証
JWT Bearer トークンを `Authorization: Bearer <token>` ヘッダーで送信する。
`/login` のみ認証不要。それ以外は全て認証必須。

## エラーハンドリング
- 401: トークン無効または期限切れ
- 403: 権限不足
- 404: 指定リソースが存在しない
- 409: 状態の競合（二重打刻など）
- 422: バリデーションエラー（フィールド別メッセージ付き）
- 500: 予期しないサーバーエラー

 * OpenAPI spec version: 1.1.0
 */

export interface AttendanceStoreRequest {
  /**
   * 退勤日時（ISO 8601）。省略時は勤務中として扱う。
   * @nullable
   */
  endTime?: string | null;
  /**
   * 備考（申請理由・特記事項など）
   * @maxLength 500
   * @nullable
   */
  note?: string | null;
  /** 出勤日時（ISO 8601） */
  startTime: string;
  /** 勤務日（YYYY-MM-DD） */
  workDate: string;
}
