/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理システムの REST API 定義。
従業員の出退勤・休憩管理、
ダッシュボード集計、カレンダー、ユーザー設定を提供する。

## 認証
JWT Bearer トークンを `Authorization: Bearer <token>` ヘッダーで送信する。
`/login` のみ認証不要。それ以外は全て認証必須。

## エラーハンドリング
- 401: トークン無効または期限切れ
- 403: 権限不足
- 404: 指定リソースが存在しない
- 409: 状態の競合（二重打刻など）
- 422: バリデーションエラー（フィールド別メッセージ付き）
- 500: 予期しないサーバーエラー

 * OpenAPI spec version: 1.1.0
 */
import type { ClockStatus } from "./clockStatus";

/**
 * 勤怠レコード。出退勤・休憩の打刻状態とローカル時刻を含む。
 */
export interface AttendanceResponse {
  /**
   * 休憩合計（分）。AttendanceBreak から再計算される。
   * @nullable
   */
  breakMinutes?: number | null;
  clockStatus: ClockStatus;
  /**
   * 退勤日時（ISO 8601）。未退勤の場合は null。
   * @nullable
   */
  endTime?: string | null;
  /** 勤怠レコード ID。新規打刻前（today で未出勤）は含まれない。 */
  id?: string;
  /**
   * 出勤日時（ISO 8601）。ローカルタイムゾーンで返す。
   * @nullable
   */
  startTime: string | null;
  /** 対象ユーザー ID。 */
  userId: string;
  /** 勤務日（YYYY-MM-DD）。タイムゾーン変換後の日付。 */
  workDate: string;
  /**
   * 実働時間（分）。出退勤の差分から breakMinutes を差し引いた値。
   * @nullable
   */
  workedMinutes?: number | null;
}
