/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 勤怠レコードの勤務区分
 */
export type AttendanceStatus =
  (typeof AttendanceStatus)[keyof typeof AttendanceStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttendanceStatus = {
  working: "working",
  out: "out",
  break: "break",
} as const;
