/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export interface AttendanceResponse {
  /**
   * 休憩合計(分)
   * @nullable
   */
  break_minutes?: number | null;
  /** @nullable */
  end_time?: string | null;
  /** @nullable */
  start_time: string | null;
  user_id: string;
  work_date: string;
  /**
   * 実働時間(分)
   * @nullable
   */
  worked_minutes?: number | null;
}
