/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export interface AttendanceStoreRequest {
  /** @nullable */
  endTime?: string | null;
  /**
   * @maxLength 500
   * @nullable
   */
  note?: string | null;
  startTime: string;
  workDate: string;
}
