/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export interface CalendarIndexRequest {
  /**
   * @minimum 1
   * @maximum 12
   */
  month: number;
  /**
   * @minimum 2000
   * @maximum 2100
   */
  year: number;
}
