/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { CalendarDay } from "./calendarDay";
import type { CalendarSummary } from "./calendarSummary";

export interface CalendarResponse {
  days: CalendarDay[];
  /**
   * @minimum 1
   * @maximum 12
   */
  month: number;
  summary: CalendarSummary;
  /**
   * @minimum 2000
   * @maximum 2100
   */
  year: number;
}
