/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

/**
 * カレンダー月次サマリー
 */
export interface CalendarSummary {
  overtimeHours: number;
  paidLeaveDays: number;
  remainingPaidLeaveDays: number;
  scheduledWorkDays: number;
  targetHours: number;
  totalWorkHours: number;
}
