/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { CalendarDayStatus } from "./calendarDayStatus";

/**
 * カレンダー1日分の情報
 */
export interface CalendarDay {
  date: string;
  dayOfWeek: string;
  isHoliday: boolean;
  isToday: boolean;
  label: string;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  note?: string | null;
  /** @nullable */
  shift?: string | null;
  status: CalendarDayStatus;
  /** @nullable */
  timeRange?: string | null;
}
