/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export type CalendarDayStatus =
  (typeof CalendarDayStatus)[keyof typeof CalendarDayStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CalendarDayStatus = {
  working: "working",
  off: "off",
  holiday: "holiday",
  pending: "pending",
} as const;
