/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePasswordRequest {
  /**
   * 現在のパスワード
   * @minLength 8
   */
  currentPassword: string;
  /**
   * 新しいパスワード
   * @minLength 8
   */
  newPassword: string;
  /**
   * 新しいパスワード（確認）
   * @minLength 8
   */
  newPasswordConfirmation: string;
}
