/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 現在の打刻状態
 */
export type ClockStatus = (typeof ClockStatus)[keyof typeof ClockStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClockStatus = {
  out: "out",
  in: "in",
  break: "break",
} as const;
