/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export interface CreateOvertimeRequest {
  /** 残業終了時刻 */
  end_time: string;
  /**
   * 申請理由
   * @maxLength 500
   * @nullable
   */
  reason?: string | null;
  /** 残業開始時刻 */
  start_time: string;
  /** 対象日 */
  work_date: string;
}
