/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export interface CreatePaidLeaveRequest {
  /**
   * 取得日数（0.5 or 1）
   * @minimum 0.5
   * @maximum 1
   */
  days: number;
  /** 取得日 */
  leave_date: string;
  /**
   * 申請理由
   * @maxLength 500
   * @nullable
   */
  reason?: string | null;
}
