/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export type DashboardResponseRecentRecordsItemStatus =
  (typeof DashboardResponseRecentRecordsItemStatus)[keyof typeof DashboardResponseRecentRecordsItemStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardResponseRecentRecordsItemStatus = {
  通常: "通常",
  残業: "残業",
  休日: "休日",
} as const;
