/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { DashboardResponseClockStatus } from "./dashboardResponseClockStatus";
import type { DashboardResponseRecentRecordsItem } from "./dashboardResponseRecentRecordsItem";
import type { DashboardResponseStats } from "./dashboardResponseStats";
import type { DashboardResponseTodayRecord } from "./dashboardResponseTodayRecord";
import type { DashboardResponseUser } from "./dashboardResponseUser";

export interface DashboardResponse {
  clockStatus: DashboardResponseClockStatus;
  pendingOvertimeRequests: number;
  recentRecords: DashboardResponseRecentRecordsItem[];
  stats: DashboardResponseStats;
  todayRecord: DashboardResponseTodayRecord;
  user: DashboardResponseUser;
}
