/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { ClockStatus } from "./clockStatus";
import type { DashboardRecentRecord } from "./dashboardRecentRecord";
import type { DashboardStats } from "./dashboardStats";
import type { DashboardTodayRecord } from "./dashboardTodayRecord";
import type { DashboardUser } from "./dashboardUser";

export interface DashboardResponse {
  clockStatus: ClockStatus;
  pendingOvertimeRequests: number;
  recentRecords: DashboardRecentRecord[];
  stats: DashboardStats;
  todayRecord: DashboardTodayRecord;
  user: DashboardUser;
}
