/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { AttendanceStatus } from "./attendanceStatus";

/**
 * 直近の勤怠レコード
 */
export interface DashboardRecentRecord {
  /** @nullable */
  clockIn: string | null;
  /** @nullable */
  clockOut: string | null;
  date: string;
  day: string;
  status: AttendanceStatus;
  /** @nullable */
  workHours: number | null;
}
