/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export type DashboardClockRequestAction =
  (typeof DashboardClockRequestAction)[keyof typeof DashboardClockRequestAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardClockRequestAction = {
  in: "in",
  out: "out",
  break_start: "break_start",
  break_end: "break_end",
} as const;
