/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { QueryYearParameter } from "./queryYearParameter";
import type { QueryMonthParameter } from "./queryMonthParameter";

export type GetCalendarParams = {
  /**
   * 対象年
   */
  year: QueryYearParameter;
  /**
   * 対象月
   */
  month: QueryMonthParameter;
};
