/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 表示言語コード
 */
export type LanguageCode = (typeof LanguageCode)[keyof typeof LanguageCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LanguageCode = {
  ja: "ja",
  en: "en",
} as const;
