/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { QueryPageParameter } from "./queryPageParameter";
import type { QueryPerPageParameter } from "./queryPerPageParameter";

export type ListLoginHistoriesParams = {
  /**
   * ページ番号（デフォルト1）
   */
  page?: QueryPageParameter;
  /**
   * 1ページあたりの件数（デフォルト20）
   */
  perPage?: QueryPerPageParameter;
};
