/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { QueryDateFromParameter } from "./queryDateFromParameter";
import type { QueryDateToParameter } from "./queryDateToParameter";

export type ListAttendancesApiParams = {
  /**
   * 検索期間の開始日
   */
  from: QueryDateFromParameter;
  /**
   * 検索期間の終了日
   */
  to: QueryDateToParameter;
};
