/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export interface LoginHistoryResponse {
  id: string;
  /**
   * IPアドレス
   * @nullable
   */
  ipAddress: string | null;
  /** ログイン日時 */
  loggedInAt: string;
  /**
   * ログアウト日時
   * @nullable
   */
  loggedOutAt?: string | null;
  /**
   * ユーザーエージェント
   * @nullable
   */
  userAgent: string | null;
}
