/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

/**
 * 残業申請のステータス
 */
export type OvertimeRequestStatus =
  (typeof OvertimeRequestStatus)[keyof typeof OvertimeRequestStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OvertimeRequestStatus = {
  pending: "pending",
  approved: "approved",
  returned: "returned",
  canceled: "canceled",
} as const;
