/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { OvertimeRequestStatus } from "./overtimeRequestStatus";

export interface OvertimeRequestResponse {
  /**
   * 承認日時
   * @nullable
   */
  approvedAt: string | null;
  /**
   * 承認者ID
   * @nullable
   */
  approvedBy: string | null;
  createdAt: string;
  durationHours: number;
  endTime: string;
  id: string;
  /** @nullable */
  reason: string | null;
  startTime: string;
  status: OvertimeRequestStatus;
  userId: string;
  workDate: string;
}
