/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

/**
 * ページネーション情報
 */
export interface PageInfo {
  /**
   * 現在のページ番号
   * @minimum 1
   */
  currentPage: number;
  /**
   * 1ページあたりの件数
   * @minimum 1
   */
  perPage: number;
  /**
   * 全件数
   * @minimum 0
   */
  totalItems: number;
  /**
   * 全ページ数
   * @minimum 0
   */
  totalPages: number;
}
