/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export interface PaidLeaveSummary {
  /** 残日数 */
  remainingDays: number;
  /** 付与日数合計 */
  totalDays: number;
  /** 使用済み日数 */
  usedDays: number;
}
