/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { ApprovalStatus } from "./approvalStatus";

export interface PaidLeaveRequestResponse {
  /**
   * 承認日時
   * @nullable
   */
  approvedAt: string | null;
  /**
   * 承認者ID
   * @nullable
   */
  approvedBy: string | null;
  createdAt: string;
  /**
   * @minimum 0.5
   * @maximum 1
   */
  days: number;
  id: string;
  leaveDate: string;
  /** @nullable */
  reason: string | null;
  status: ApprovalStatus;
  userId: string;
}
