/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export type SettingsResponseLanguage =
  (typeof SettingsResponseLanguage)[keyof typeof SettingsResponseLanguage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SettingsResponseLanguage = {
  ja: "ja",
  en: "en",
} as const;
