/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export type SettingsResponseTheme =
  (typeof SettingsResponseTheme)[keyof typeof SettingsResponseTheme];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SettingsResponseTheme = {
  light: "light",
  dark: "dark",
} as const;
