/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { TeamMemberStatus } from "./teamMemberStatus";

export interface TeamMember {
  /** @nullable */
  clockInTime?: string | null;
  department: string;
  email: string;
  id: string;
  name: string;
  role: string;
  status: TeamMemberStatus;
}
