/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export type TeamMemberStatus =
  (typeof TeamMemberStatus)[keyof typeof TeamMemberStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeamMemberStatus = {
  working: "working",
  break: "break",
  off: "off",
  leave: "leave",
} as const;
