/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

/**
 * UIテーマ設定
 */
export type ThemeType = (typeof ThemeType)[keyof typeof ThemeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ThemeType = {
  light: "light",
  dark: "dark",
} as const;
