/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateSettingsRequestLanguage } from "./updateSettingsRequestLanguage";
import type { UpdateSettingsRequestNotifications } from "./updateSettingsRequestNotifications";
import type { UpdateSettingsRequestProfile } from "./updateSettingsRequestProfile";
import type { UpdateSettingsRequestTheme } from "./updateSettingsRequestTheme";

export interface UpdateSettingsRequest {
  language: UpdateSettingsRequestLanguage;
  notifications: UpdateSettingsRequestNotifications;
  profile: UpdateSettingsRequestProfile;
  theme: UpdateSettingsRequestTheme;
}
