/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { LanguageCode } from "./languageCode";
import type { SettingsNotifications } from "./settingsNotifications";
import type { UpdateSettingsProfile } from "./updateSettingsProfile";
import type { ThemeType } from "./themeType";

export interface UpdateSettingsRequest {
  language: LanguageCode;
  notifications: SettingsNotifications;
  profile: UpdateSettingsProfile;
  theme: ThemeType;
}
