/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateSettingsRequestTheme =
  (typeof UpdateSettingsRequestTheme)[keyof typeof UpdateSettingsRequestTheme];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSettingsRequestTheme = {
  light: "light",
  dark: "dark",
  system: "system",
} as const;
