/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */

/**
 * ユーザープロフィール更新（リクエスト用）
 */
export interface UpdateSettingsProfile {
  /** @maxLength 255 */
  email: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  name: string;
}
