/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseUser } from "./userResponseUser";

/**
 * ユーザー情報
 */
export interface UserResponse {
  user: UserResponseUser;
}
