/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理システムの REST API 定義。
従業員の出退勤・休憩管理、有給休暇・残業の申請承認、
ダッシュボード集計、カレンダー、ユーザー設定を提供する。

## 認証
JWT Bearer トークンを `Authorization: Bearer <token>` ヘッダーで送信する。
`/login` のみ認証不要。それ以外は全て認証必須。

## エラーハンドリング
- 401: トークン無効または期限切れ
- 403: 権限不足（承認権限が必要な操作）
- 404: 指定リソースが存在しない
- 409: 状態の競合（二重打刻など）
- 422: バリデーションエラー（フィールド別メッセージ付き）
- 500: 予期しないサーバーエラー

 * OpenAPI spec version: 1.1.0
 */
import type { LanguageCode } from "./languageCode";
import type { ThemeType } from "./themeType";

/**
 * ユーザー設定
 * @nullable
 */
export type UserResponseUserSettings = {
  language?: LanguageCode;
  theme?: ThemeType;
} | null;
