/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { LanguageCode } from "./languageCode";
import type { ThemeType } from "./themeType";

/**
 * ユーザー設定
 * @nullable
 */
export type UserResponseUserSettings = {
  language?: LanguageCode;
  theme?: ThemeType;
} | null;
