/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * TimeAttendance API
 * 勤怠管理API
 * OpenAPI spec version: 1.0.0
 */
import type { UserResponseUserSettings } from "./userResponseUserSettings";

export type UserResponseUser = {
  /** メールアドレス */
  email: string;
  /** ユーザーID */
  id: string;
  /** 表示名 */
  name: string;
  /** 付与ロール名一覧 */
  roles: string[];
  /**
   * ユーザー設定
   * @nullable
   */
  settings?: UserResponseUserSettings;
};
